/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`customer_portal_seats_assign_seat`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustomerPortalSeatsAssignSeatError {
    Status400(),
    Status401(),
    Status403(),
    Status404(),
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`customer_portal_seats_list_claimed_subscriptions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustomerPortalSeatsListClaimedSubscriptionsError {
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`customer_portal_seats_list_seats`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustomerPortalSeatsListSeatsError {
    Status401(),
    Status403(),
    Status404(),
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`customer_portal_seats_resend_invitation`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustomerPortalSeatsResendInvitationError {
    Status400(),
    Status401(),
    Status403(),
    Status404(),
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`customer_portal_seats_revoke_seat`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustomerPortalSeatsRevokeSeatError {
    Status401(),
    Status403(),
    Status404(),
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// **Scopes**: `customer_portal:write`
pub async fn customer_portal_seats_assign_seat(
    configuration: &configuration::Configuration,
    seat_assign: models::SeatAssign,
) -> Result<models::CustomerSeat, Error<CustomerPortalSeatsAssignSeatError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_seat_assign = seat_assign;

    let uri_str = format!("{}/v1/customer-portal/seats", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_seat_assign);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CustomerSeat`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CustomerSeat`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustomerPortalSeatsAssignSeatError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// List all subscriptions where the authenticated customer has claimed a seat.  **Scopes**: `customer_portal:read` `customer_portal:write`
pub async fn customer_portal_seats_list_claimed_subscriptions(
    configuration: &configuration::Configuration,
) -> Result<
    Vec<models::CustomerSubscription>,
    Error<CustomerPortalSeatsListClaimedSubscriptionsError>,
> {
    let uri_str = format!(
        "{}/v1/customer-portal/seats/subscriptions",
        configuration.base_path
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::CustomerSubscription&gt;`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::CustomerSubscription&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustomerPortalSeatsListClaimedSubscriptionsError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// **Scopes**: `customer_portal:read` `customer_portal:write`
pub async fn customer_portal_seats_list_seats(
    configuration: &configuration::Configuration,
    subscription_id: Option<&str>,
    order_id: Option<&str>,
) -> Result<models::SeatsList, Error<CustomerPortalSeatsListSeatsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_subscription_id = subscription_id;
    let p_query_order_id = order_id;

    let uri_str = format!("{}/v1/customer-portal/seats", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_subscription_id {
        req_builder = req_builder.query(&[("subscription_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_order_id {
        req_builder = req_builder.query(&[("order_id", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::SeatsList`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::SeatsList`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustomerPortalSeatsListSeatsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// **Scopes**: `customer_portal:write`
pub async fn customer_portal_seats_resend_invitation(
    configuration: &configuration::Configuration,
    seat_id: &str,
) -> Result<models::CustomerSeat, Error<CustomerPortalSeatsResendInvitationError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_seat_id = seat_id;

    let uri_str = format!(
        "{}/v1/customer-portal/seats/{seat_id}/resend",
        configuration.base_path,
        seat_id = crate::apis::urlencode(p_path_seat_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CustomerSeat`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CustomerSeat`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustomerPortalSeatsResendInvitationError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// **Scopes**: `customer_portal:write`
pub async fn customer_portal_seats_revoke_seat(
    configuration: &configuration::Configuration,
    seat_id: &str,
) -> Result<models::CustomerSeat, Error<CustomerPortalSeatsRevokeSeatError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_seat_id = seat_id;

    let uri_str = format!(
        "{}/v1/customer-portal/seats/{seat_id}",
        configuration.base_path,
        seat_id = crate::apis::urlencode(p_path_seat_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CustomerSeat`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CustomerSeat`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustomerPortalSeatsRevokeSeatError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
