/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlreadyActiveSubscriptionError {
    #[serde(rename = "error")]
    pub error: Error,
    #[serde(rename = "detail")]
    pub detail: String,
}

impl AlreadyActiveSubscriptionError {
    pub fn new(error: Error, detail: String) -> AlreadyActiveSubscriptionError {
        AlreadyActiveSubscriptionError { error, detail }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Error {
    #[serde(rename = "AlreadyActiveSubscriptionError")]
    AlreadyActiveSubscriptionError,
}

impl Default for Error {
    fn default() -> Error {
        Self::AlreadyActiveSubscriptionError
    }
}
