/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BenefitLicenseKeyExpirationProperties {
    #[serde(rename = "ttl")]
    pub ttl: i32,
    #[serde(rename = "timeframe")]
    pub timeframe: Timeframe,
}

impl BenefitLicenseKeyExpirationProperties {
    pub fn new(ttl: i32, timeframe: Timeframe) -> BenefitLicenseKeyExpirationProperties {
        BenefitLicenseKeyExpirationProperties { ttl, timeframe }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Timeframe {
    #[serde(rename = "year")]
    Year,
    #[serde(rename = "month")]
    Month,
    #[serde(rename = "day")]
    Day,
}

impl Default for Timeframe {
    fn default() -> Timeframe {
        Self::Year
    }
}
