/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BenefitIdFilter1 : Filter by benefit ID.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BenefitIdFilter1 {}

impl BenefitIdFilter1 {
    /// Filter by benefit ID.
    pub fn new() -> BenefitIdFilter1 {
        BenefitIdFilter1 {}
    }
}
