/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BenefitDiscordCreateProperties : Properties to create a benefit of type `discord`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BenefitDiscordCreateProperties {
    #[serde(rename = "guild_token")]
    pub guild_token: String,
    /// The ID of the Discord role to grant.
    #[serde(rename = "role_id")]
    pub role_id: String,
    /// Whether to kick the member from the Discord server on revocation.
    #[serde(rename = "kick_member")]
    pub kick_member: bool,
}

impl BenefitDiscordCreateProperties {
    /// Properties to create a benefit of type `discord`.
    pub fn new(
        guild_token: String,
        role_id: String,
        kick_member: bool,
    ) -> BenefitDiscordCreateProperties {
        BenefitDiscordCreateProperties {
            guild_token,
            role_id,
            kick_member,
        }
    }
}
