/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Benefit {
    /// The ID of the benefit.
    #[serde(rename = "id")]
    pub id: String,
    /// Creation timestamp of the object.
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "modified_at")]
    pub modified_at: String,
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The description of the benefit.
    #[serde(rename = "description")]
    pub description: String,
    /// Whether the benefit is selectable when creating a product.
    #[serde(rename = "selectable")]
    pub selectable: bool,
    /// Whether the benefit is deletable.
    #[serde(rename = "deletable")]
    pub deletable: bool,
    /// The ID of the organization owning the benefit.
    #[serde(rename = "organization_id")]
    pub organization_id: String,
    #[serde(rename = "metadata")]
    pub metadata: std::collections::HashMap<String, models::MetadataValue>,
    #[serde(rename = "properties")]
    pub properties: Box<models::BenefitMeterCreditProperties>,
}

impl Benefit {
    pub fn new(
        id: String,
        created_at: String,
        modified_at: String,
        r#type: Type,
        description: String,
        selectable: bool,
        deletable: bool,
        organization_id: String,
        metadata: std::collections::HashMap<String, models::MetadataValue>,
        properties: models::BenefitMeterCreditProperties,
    ) -> Benefit {
        Benefit {
            id,
            created_at,
            modified_at,
            r#type,
            description,
            selectable,
            deletable,
            organization_id,
            metadata,
            properties: Box::new(properties),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "custom")]
    Custom,
    #[serde(rename = "discord")]
    Discord,
    #[serde(rename = "github_repository")]
    GithubRepository,
    #[serde(rename = "downloadables")]
    Downloadables,
    #[serde(rename = "license_keys")]
    LicenseKeys,
    #[serde(rename = "meter_credit")]
    MeterCredit,
}

impl Default for Type {
    fn default() -> Type {
        Self::Custom
    }
}
