/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BenefitLicenseKeysCreateProperties {
    #[serde(
        rename = "prefix",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub prefix: Option<Option<String>>,
    #[serde(
        rename = "expires",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expires: Option<Option<Box<models::BenefitLicenseKeyExpirationProperties>>>,
    #[serde(
        rename = "activations",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub activations: Option<Option<Box<models::BenefitLicenseKeyActivationCreateProperties>>>,
    #[serde(
        rename = "limit_usage",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub limit_usage: Option<Option<i32>>,
}

impl BenefitLicenseKeysCreateProperties {
    pub fn new() -> BenefitLicenseKeysCreateProperties {
        BenefitLicenseKeysCreateProperties {
            prefix: None,
            expires: None,
            activations: None,
            limit_usage: None,
        }
    }
}
