/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BenefitCustom : A benefit of type `custom`.  Use it to grant any kind of benefit that doesn't fit in the other types.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BenefitCustom {
    /// The ID of the benefit.
    #[serde(rename = "id")]
    pub id: String,
    /// Creation timestamp of the object.
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "modified_at", deserialize_with = "Option::deserialize")]
    pub modified_at: Option<String>,
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The description of the benefit.
    #[serde(rename = "description")]
    pub description: String,
    /// Whether the benefit is selectable when creating a product.
    #[serde(rename = "selectable")]
    pub selectable: bool,
    /// Whether the benefit is deletable.
    #[serde(rename = "deletable")]
    pub deletable: bool,
    /// The ID of the organization owning the benefit.
    #[serde(rename = "organization_id")]
    pub organization_id: String,
    #[serde(rename = "metadata")]
    pub metadata: std::collections::HashMap<String, models::MetadataValue>,
    #[serde(rename = "properties")]
    pub properties: Box<models::BenefitCustomProperties>,
}

impl BenefitCustom {
    /// A benefit of type `custom`.  Use it to grant any kind of benefit that doesn't fit in the other types.
    pub fn new(
        id: String,
        created_at: String,
        modified_at: Option<String>,
        r#type: Type,
        description: String,
        selectable: bool,
        deletable: bool,
        organization_id: String,
        metadata: std::collections::HashMap<String, models::MetadataValue>,
        properties: models::BenefitCustomProperties,
    ) -> BenefitCustom {
        BenefitCustom {
            id,
            created_at,
            modified_at,
            r#type,
            description,
            selectable,
            deletable,
            organization_id,
            metadata,
            properties: Box::new(properties),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "custom")]
    Custom,
}

impl Default for Type {
    fn default() -> Type {
        Self::Custom
    }
}
