/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BenefitGitHubRepositorySubscriberProperties : Properties available to subscribers for a benefit of type `github_repository`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BenefitGitHubRepositorySubscriberProperties {
    /// The owner of the repository.
    #[serde(rename = "repository_owner")]
    pub repository_owner: String,
    /// The name of the repository.
    #[serde(rename = "repository_name")]
    pub repository_name: String,
}

impl BenefitGitHubRepositorySubscriberProperties {
    /// Properties available to subscribers for a benefit of type `github_repository`.
    pub fn new(
        repository_owner: String,
        repository_name: String,
    ) -> BenefitGitHubRepositorySubscriberProperties {
        BenefitGitHubRepositorySubscriberProperties {
            repository_owner,
            repository_name,
        }
    }
}
