/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BenefitSortProperty {
    #[serde(rename = "created_at")]
    CreatedAt,
    #[serde(rename = "-created_at")]
    CreatedAt2,
    #[serde(rename = "description")]
    Description,
    #[serde(rename = "-description")]
    Description2,
    #[serde(rename = "type")]
    Type,
    #[serde(rename = "-type")]
    Type2,
}

impl std::fmt::Display for BenefitSortProperty {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CreatedAt => write!(f, "created_at"),
            Self::CreatedAt2 => write!(f, "-created_at"),
            Self::Description => write!(f, "description"),
            Self::Description2 => write!(f, "-description"),
            Self::Type => write!(f, "type"),
            Self::Type2 => write!(f, "-type"),
        }
    }
}

impl Default for BenefitSortProperty {
    fn default() -> BenefitSortProperty {
        Self::CreatedAt
    }
}
