/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BenefitDiscordSubscriberProperties : Properties available to subscribers for a benefit of type `discord`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BenefitDiscordSubscriberProperties {
    /// The ID of the Discord server.
    #[serde(rename = "guild_id")]
    pub guild_id: String,
}

impl BenefitDiscordSubscriberProperties {
    /// Properties available to subscribers for a benefit of type `discord`.
    pub fn new(guild_id: String) -> BenefitDiscordSubscriberProperties {
        BenefitDiscordSubscriberProperties { guild_id }
    }
}
