/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BenefitDownloadablesSubscriberProperties {
    #[serde(rename = "active_files")]
    pub active_files: Vec<String>,
}

impl BenefitDownloadablesSubscriberProperties {
    pub fn new(active_files: Vec<String>) -> BenefitDownloadablesSubscriberProperties {
        BenefitDownloadablesSubscriberProperties { active_files }
    }
}
