/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BenefitDownloadablesCreateProperties {
    #[serde(rename = "archived", skip_serializing_if = "Option::is_none")]
    pub archived: Option<std::collections::HashMap<String, bool>>,
    #[serde(rename = "files")]
    pub files: Vec<String>,
}

impl BenefitDownloadablesCreateProperties {
    pub fn new(files: Vec<String>) -> BenefitDownloadablesCreateProperties {
        BenefitDownloadablesCreateProperties {
            archived: None,
            files,
        }
    }
}
