/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BenefitCustomCreate : Schema to create a benefit of type `custom`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BenefitCustomCreate {
    /// Key-value object allowing you to store additional information.  The key must be a string with a maximum length of **40 characters**. The value must be either:  * A string with a maximum length of **500 characters** * An integer * A floating-point number * A boolean  You can store up to **50 key-value pairs**.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, models::MetadataValue1>>,
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The description of the benefit. Will be displayed on products having this benefit.
    #[serde(rename = "description")]
    pub description: String,
    /// The organization ID.
    #[serde(
        rename = "organization_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub organization_id: Option<Option<String>>,
    #[serde(rename = "properties")]
    pub properties: Box<models::BenefitCustomCreateProperties>,
}

impl BenefitCustomCreate {
    /// Schema to create a benefit of type `custom`.
    pub fn new(
        r#type: Type,
        description: String,
        properties: models::BenefitCustomCreateProperties,
    ) -> BenefitCustomCreate {
        BenefitCustomCreate {
            metadata: None,
            r#type,
            description,
            organization_id: None,
            properties: Box::new(properties),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "custom")]
    Custom,
}

impl Default for Type {
    fn default() -> Type {
        Self::Custom
    }
}
