/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BenefitGrantGitHubRepositoryWebhook {
    /// Creation timestamp of the object.
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "modified_at", deserialize_with = "Option::deserialize")]
    pub modified_at: Option<String>,
    /// The ID of the grant.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(
        rename = "granted_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub granted_at: Option<Option<String>>,
    /// Whether the benefit is granted.
    #[serde(rename = "is_granted")]
    pub is_granted: bool,
    #[serde(
        rename = "revoked_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub revoked_at: Option<Option<String>>,
    /// Whether the benefit is revoked.
    #[serde(rename = "is_revoked")]
    pub is_revoked: bool,
    #[serde(rename = "subscription_id", deserialize_with = "Option::deserialize")]
    pub subscription_id: Option<String>,
    #[serde(rename = "order_id", deserialize_with = "Option::deserialize")]
    pub order_id: Option<String>,
    /// The ID of the customer concerned by this grant.
    #[serde(rename = "customer_id")]
    pub customer_id: String,
    /// The ID of the benefit concerned by this grant.
    #[serde(rename = "benefit_id")]
    pub benefit_id: String,
    #[serde(
        rename = "error",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub error: Option<Option<Box<models::BenefitGrantError>>>,
    #[serde(rename = "customer")]
    pub customer: Box<models::Customer>,
    #[serde(rename = "benefit")]
    pub benefit: Box<models::BenefitGitHubRepository>,
    #[serde(rename = "properties")]
    pub properties: Box<models::BenefitGrantGitHubRepositoryProperties>,
    #[serde(
        rename = "previous_properties",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub previous_properties: Option<Option<Box<models::BenefitGrantGitHubRepositoryProperties>>>,
}

impl BenefitGrantGitHubRepositoryWebhook {
    pub fn new(
        created_at: String,
        modified_at: Option<String>,
        id: String,
        is_granted: bool,
        is_revoked: bool,
        subscription_id: Option<String>,
        order_id: Option<String>,
        customer_id: String,
        benefit_id: String,
        customer: models::Customer,
        benefit: models::BenefitGitHubRepository,
        properties: models::BenefitGrantGitHubRepositoryProperties,
    ) -> BenefitGrantGitHubRepositoryWebhook {
        BenefitGrantGitHubRepositoryWebhook {
            created_at,
            modified_at,
            id,
            granted_at: None,
            is_granted,
            revoked_at: None,
            is_revoked,
            subscription_id,
            order_id,
            customer_id,
            benefit_id,
            error: None,
            customer: Box::new(customer),
            benefit: Box::new(benefit),
            properties: Box::new(properties),
            previous_properties: None,
        }
    }
}
