/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BenefitCustomSubscriberProperties : Properties available to subscribers for a benefit of type `custom`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BenefitCustomSubscriberProperties {
    #[serde(rename = "note", deserialize_with = "Option::deserialize")]
    pub note: Option<String>,
}

impl BenefitCustomSubscriberProperties {
    /// Properties available to subscribers for a benefit of type `custom`.
    pub fn new(note: Option<String>) -> BenefitCustomSubscriberProperties {
        BenefitCustomSubscriberProperties { note }
    }
}
