/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum BenefitCreate {
    #[serde(rename = "custom")]
    Custom(Box<models::BenefitCustomCreate>),
    #[serde(rename = "discord")]
    Discord(Box<models::BenefitDiscordCreate>),
    #[serde(rename = "github_repository")]
    GithubRepository(Box<models::BenefitGitHubRepositoryCreate>),
    #[serde(rename = "downloadables")]
    Downloadables(Box<models::BenefitDownloadablesCreate>),
    #[serde(rename = "license_keys")]
    LicenseKeys(Box<models::BenefitLicenseKeysCreate>),
    #[serde(rename = "meter_credit")]
    MeterCredit(Box<models::BenefitMeterCreditCreate>),
}

impl Default for BenefitCreate {
    fn default() -> Self {
        Self::Custom(Default::default())
    }
}
