/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CardPayment : Schema of a payment with a card payment method.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CardPayment {
    /// Creation timestamp of the object.
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "modified_at", deserialize_with = "Option::deserialize")]
    pub modified_at: Option<String>,
    /// The ID of the object.
    #[serde(rename = "id")]
    pub id: String,
    /// The payment processor.
    #[serde(rename = "processor")]
    pub processor: models::PaymentProcessor,
    /// The payment status.
    #[serde(rename = "status")]
    pub status: models::PaymentStatus,
    /// The payment amount in cents.
    #[serde(rename = "amount")]
    pub amount: i32,
    /// The payment currency. Currently, only `usd` is supported.
    #[serde(rename = "currency")]
    pub currency: String,
    /// The payment method used.
    #[serde(rename = "method")]
    pub method: Method,
    #[serde(rename = "decline_reason", deserialize_with = "Option::deserialize")]
    pub decline_reason: Option<String>,
    #[serde(rename = "decline_message", deserialize_with = "Option::deserialize")]
    pub decline_message: Option<String>,
    /// The ID of the organization that owns the payment.
    #[serde(rename = "organization_id")]
    pub organization_id: String,
    #[serde(rename = "checkout_id", deserialize_with = "Option::deserialize")]
    pub checkout_id: Option<String>,
    #[serde(rename = "order_id", deserialize_with = "Option::deserialize")]
    pub order_id: Option<String>,
    /// Additional metadata from the payment processor for internal use.
    #[serde(rename = "processor_metadata", skip_serializing_if = "Option::is_none")]
    pub processor_metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Additional metadata for the card payment method.
    #[serde(rename = "method_metadata")]
    pub method_metadata: Box<models::CardPaymentMetadata>,
}

impl CardPayment {
    /// Schema of a payment with a card payment method.
    pub fn new(
        created_at: String,
        modified_at: Option<String>,
        id: String,
        processor: models::PaymentProcessor,
        status: models::PaymentStatus,
        amount: i32,
        currency: String,
        method: Method,
        decline_reason: Option<String>,
        decline_message: Option<String>,
        organization_id: String,
        checkout_id: Option<String>,
        order_id: Option<String>,
        method_metadata: models::CardPaymentMetadata,
    ) -> CardPayment {
        CardPayment {
            created_at,
            modified_at,
            id,
            processor,
            status,
            amount,
            currency,
            method,
            decline_reason,
            decline_message,
            organization_id,
            checkout_id,
            order_id,
            processor_metadata: None,
            method_metadata: Box::new(method_metadata),
        }
    }
}
/// The payment method used.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Method {
    #[serde(rename = "card")]
    Card,
}

impl Default for Method {
    fn default() -> Method {
        Self::Card
    }
}
