/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CheckoutUpdatePublic : Update an existing checkout session using the client secret.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckoutUpdatePublic {
    /// Key-value object storing custom field values.
    #[serde(rename = "custom_field_data", skip_serializing_if = "Option::is_none")]
    pub custom_field_data: Option<std::collections::HashMap<String, models::CustomFieldDataValue>>,
    #[serde(
        rename = "product_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub product_id: Option<Option<String>>,
    #[serde(
        rename = "product_price_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub product_price_id: Option<Option<String>>,
    /// Amount in cents, before discounts and taxes. Only useful for custom prices, it'll be ignored for fixed and free prices.
    #[serde(
        rename = "amount",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub amount: Option<Option<i32>>,
    #[serde(
        rename = "seats",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub seats: Option<Option<i32>>,
    #[serde(
        rename = "is_business_customer",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_business_customer: Option<Option<bool>>,
    /// Name of the customer.
    #[serde(
        rename = "customer_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub customer_name: Option<Option<String>>,
    /// Email address of the customer.
    #[serde(
        rename = "customer_email",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub customer_email: Option<Option<String>>,
    #[serde(
        rename = "customer_billing_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub customer_billing_name: Option<Option<String>>,
    /// Billing address of the customer.
    #[serde(
        rename = "customer_billing_address",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub customer_billing_address: Option<Option<Box<models::AddressInput>>>,
    #[serde(
        rename = "customer_tax_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub customer_tax_id: Option<Option<String>>,
    #[serde(
        rename = "discount_code",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub discount_code: Option<Option<String>>,
}

impl CheckoutUpdatePublic {
    /// Update an existing checkout session using the client secret.
    pub fn new() -> CheckoutUpdatePublic {
        CheckoutUpdatePublic {
            custom_field_data: None,
            product_id: None,
            product_price_id: None,
            amount: None,
            seats: None,
            is_business_customer: None,
            customer_name: None,
            customer_email: None,
            customer_billing_name: None,
            customer_billing_address: None,
            customer_tax_id: None,
            discount_code: None,
        }
    }
}
