/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CheckoutCustomerBillingAddressFields : Deprecated: Use CheckoutBillingAddressFields instead.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckoutCustomerBillingAddressFields {
    #[serde(rename = "country")]
    pub country: bool,
    #[serde(rename = "state")]
    pub state: bool,
    #[serde(rename = "city")]
    pub city: bool,
    #[serde(rename = "postal_code")]
    pub postal_code: bool,
    #[serde(rename = "line1")]
    pub line1: bool,
    #[serde(rename = "line2")]
    pub line2: bool,
}

impl CheckoutCustomerBillingAddressFields {
    /// Deprecated: Use CheckoutBillingAddressFields instead.
    pub fn new(
        country: bool,
        state: bool,
        city: bool,
        postal_code: bool,
        line1: bool,
        line2: bool,
    ) -> CheckoutCustomerBillingAddressFields {
        CheckoutCustomerBillingAddressFields {
            country,
            state,
            city,
            postal_code,
            line1,
            line2,
        }
    }
}
