/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CheckoutSortProperty {
    #[serde(rename = "created_at")]
    CreatedAt,
    #[serde(rename = "-created_at")]
    CreatedAt2,
    #[serde(rename = "expires_at")]
    ExpiresAt,
    #[serde(rename = "-expires_at")]
    ExpiresAt2,
    #[serde(rename = "status")]
    Status,
    #[serde(rename = "-status")]
    Status2,
}

impl std::fmt::Display for CheckoutSortProperty {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CreatedAt => write!(f, "created_at"),
            Self::CreatedAt2 => write!(f, "-created_at"),
            Self::ExpiresAt => write!(f, "expires_at"),
            Self::ExpiresAt2 => write!(f, "-expires_at"),
            Self::Status => write!(f, "status"),
            Self::Status2 => write!(f, "-status"),
        }
    }
}

impl Default for CheckoutSortProperty {
    fn default() -> CheckoutSortProperty {
        Self::CreatedAt
    }
}
