/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CheckoutDiscountFixedRepeatDuration : Schema for a fixed amount discount that is applied on every invoice for a certain number of months.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckoutDiscountFixedRepeatDuration {
    #[serde(rename = "duration")]
    pub duration: models::DiscountDuration,
    #[serde(rename = "duration_in_months")]
    pub duration_in_months: i32,
    #[serde(rename = "type")]
    pub r#type: models::DiscountType,
    #[serde(rename = "amount")]
    pub amount: i32,
    #[serde(rename = "currency")]
    pub currency: String,
    /// The ID of the object.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "code", deserialize_with = "Option::deserialize")]
    pub code: Option<String>,
}

impl CheckoutDiscountFixedRepeatDuration {
    /// Schema for a fixed amount discount that is applied on every invoice for a certain number of months.
    pub fn new(
        duration: models::DiscountDuration,
        duration_in_months: i32,
        r#type: models::DiscountType,
        amount: i32,
        currency: String,
        id: String,
        name: String,
        code: Option<String>,
    ) -> CheckoutDiscountFixedRepeatDuration {
        CheckoutDiscountFixedRepeatDuration {
            duration,
            duration_in_months,
            r#type,
            amount,
            currency,
            id,
            name,
            code,
        }
    }
}
