/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomFieldTextProperties {
    #[serde(rename = "form_label", skip_serializing_if = "Option::is_none")]
    pub form_label: Option<String>,
    #[serde(rename = "form_help_text", skip_serializing_if = "Option::is_none")]
    pub form_help_text: Option<String>,
    #[serde(rename = "form_placeholder", skip_serializing_if = "Option::is_none")]
    pub form_placeholder: Option<String>,
    #[serde(rename = "textarea", skip_serializing_if = "Option::is_none")]
    pub textarea: Option<bool>,
    #[serde(rename = "min_length", skip_serializing_if = "Option::is_none")]
    pub min_length: Option<i32>,
    #[serde(rename = "max_length", skip_serializing_if = "Option::is_none")]
    pub max_length: Option<i32>,
}

impl CustomFieldTextProperties {
    pub fn new() -> CustomFieldTextProperties {
        CustomFieldTextProperties {
            form_label: None,
            form_help_text: None,
            form_placeholder: None,
            textarea: None,
            min_length: None,
            max_length: None,
        }
    }
}
