/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerPaymentMethodConfirm {
    #[serde(rename = "setup_intent_id")]
    pub setup_intent_id: String,
    #[serde(rename = "set_default")]
    pub set_default: bool,
}

impl CustomerPaymentMethodConfirm {
    pub fn new(setup_intent_id: String, set_default: bool) -> CustomerPaymentMethodConfirm {
        CustomerPaymentMethodConfirm {
            setup_intent_id,
            set_default,
        }
    }
}
