/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CustomerBenefitGrantSortProperty {
    #[serde(rename = "granted_at")]
    GrantedAt,
    #[serde(rename = "-granted_at")]
    GrantedAt2,
    #[serde(rename = "type")]
    Type,
    #[serde(rename = "-type")]
    Type2,
    #[serde(rename = "organization")]
    Organization,
    #[serde(rename = "-organization")]
    Organization2,
}

impl std::fmt::Display for CustomerBenefitGrantSortProperty {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::GrantedAt => write!(f, "granted_at"),
            Self::GrantedAt2 => write!(f, "-granted_at"),
            Self::Type => write!(f, "type"),
            Self::Type2 => write!(f, "-type"),
            Self::Organization => write!(f, "organization"),
            Self::Organization2 => write!(f, "-organization"),
        }
    }
}

impl Default for CustomerBenefitGrantSortProperty {
    fn default() -> CustomerBenefitGrantSortProperty {
        Self::GrantedAt
    }
}
