/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerPortalCustomer {
    /// Creation timestamp of the object.
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "modified_at", deserialize_with = "Option::deserialize")]
    pub modified_at: Option<String>,
    /// The ID of the object.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "email_verified")]
    pub email_verified: bool,
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<String>,
    #[serde(rename = "billing_name", deserialize_with = "Option::deserialize")]
    pub billing_name: Option<String>,
    #[serde(rename = "billing_address", deserialize_with = "Option::deserialize")]
    pub billing_address: Option<Box<models::Address>>,
    #[serde(rename = "tax_id", deserialize_with = "Option::deserialize")]
    pub tax_id: Option<Vec<serde_json::Value>>,
    #[serde(rename = "oauth_accounts")]
    pub oauth_accounts: std::collections::HashMap<String, models::CustomerPortalOAuthAccount>,
    #[serde(
        rename = "default_payment_method_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_payment_method_id: Option<Option<String>>,
}

impl CustomerPortalCustomer {
    pub fn new(
        created_at: String,
        modified_at: Option<String>,
        id: String,
        email: String,
        email_verified: bool,
        name: Option<String>,
        billing_name: Option<String>,
        billing_address: Option<models::Address>,
        tax_id: Option<Vec<serde_json::Value>>,
        oauth_accounts: std::collections::HashMap<String, models::CustomerPortalOAuthAccount>,
    ) -> CustomerPortalCustomer {
        CustomerPortalCustomer {
            created_at,
            modified_at,
            id,
            email,
            email_verified,
            name,
            billing_name,
            billing_address: billing_address.map(Box::new),
            tax_id,
            oauth_accounts,
            default_payment_method_id: None,
        }
    }
}
