/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerBenefitGrantMeterCreditUpdate {
    #[serde(rename = "benefit_type")]
    pub benefit_type: BenefitType,
}

impl CustomerBenefitGrantMeterCreditUpdate {
    pub fn new(benefit_type: BenefitType) -> CustomerBenefitGrantMeterCreditUpdate {
        CustomerBenefitGrantMeterCreditUpdate { benefit_type }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BenefitType {
    #[serde(rename = "meter_credit")]
    MeterCredit,
}

impl Default for BenefitType {
    fn default() -> BenefitType {
        Self::MeterCredit
    }
}
