/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CustomerSubscriptionSortProperty {
    #[serde(rename = "started_at")]
    StartedAt,
    #[serde(rename = "-started_at")]
    StartedAt2,
    #[serde(rename = "amount")]
    Amount,
    #[serde(rename = "-amount")]
    Amount2,
    #[serde(rename = "status")]
    Status,
    #[serde(rename = "-status")]
    Status2,
    #[serde(rename = "organization")]
    Organization,
    #[serde(rename = "-organization")]
    Organization2,
    #[serde(rename = "product")]
    Product,
    #[serde(rename = "-product")]
    Product2,
}

impl std::fmt::Display for CustomerSubscriptionSortProperty {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::StartedAt => write!(f, "started_at"),
            Self::StartedAt2 => write!(f, "-started_at"),
            Self::Amount => write!(f, "amount"),
            Self::Amount2 => write!(f, "-amount"),
            Self::Status => write!(f, "status"),
            Self::Status2 => write!(f, "-status"),
            Self::Organization => write!(f, "organization"),
            Self::Organization2 => write!(f, "-organization"),
            Self::Product => write!(f, "product"),
            Self::Product2 => write!(f, "-product"),
        }
    }
}

impl Default for CustomerSubscriptionSortProperty {
    fn default() -> CustomerSubscriptionSortProperty {
        Self::StartedAt
    }
}
