/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerPortalCustomerUpdate {
    #[serde(
        rename = "billing_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub billing_name: Option<Option<String>>,
    #[serde(
        rename = "billing_address",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub billing_address: Option<Option<Box<models::AddressInput>>>,
    #[serde(
        rename = "tax_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tax_id: Option<Option<String>>,
}

impl CustomerPortalCustomerUpdate {
    pub fn new() -> CustomerPortalCustomerUpdate {
        CustomerPortalCustomerUpdate {
            billing_name: None,
            billing_address: None,
            tax_id: None,
        }
    }
}
