/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomerSession : A customer session that can be used to authenticate as a customer.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerSession {
    /// Creation timestamp of the object.
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "modified_at", deserialize_with = "Option::deserialize")]
    pub modified_at: Option<String>,
    /// The ID of the object.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "expires_at")]
    pub expires_at: String,
    #[serde(rename = "return_url", deserialize_with = "Option::deserialize")]
    pub return_url: Option<String>,
    #[serde(rename = "customer_portal_url")]
    pub customer_portal_url: String,
    #[serde(rename = "customer_id")]
    pub customer_id: String,
    #[serde(rename = "customer")]
    pub customer: Box<models::Customer>,
}

impl CustomerSession {
    /// A customer session that can be used to authenticate as a customer.
    pub fn new(
        created_at: String,
        modified_at: Option<String>,
        id: String,
        token: String,
        expires_at: String,
        return_url: Option<String>,
        customer_portal_url: String,
        customer_id: String,
        customer: models::Customer,
    ) -> CustomerSession {
        CustomerSession {
            created_at,
            modified_at,
            id,
            token,
            expires_at,
            return_url,
            customer_portal_url,
            customer_id,
            customer: Box::new(customer),
        }
    }
}
