/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomFieldSelectOption {
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "label")]
    pub label: String,
}

impl CustomFieldSelectOption {
    pub fn new(value: String, label: String) -> CustomFieldSelectOption {
        CustomFieldSelectOption { value, label }
    }
}
