/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerSubscriptionUpdate {
    /// Update subscription to another product.
    #[serde(rename = "product_id")]
    pub product_id: String,
    /// Update the number of seats for this subscription.
    #[serde(rename = "seats")]
    pub seats: i32,
    #[serde(rename = "proration_behavior", skip_serializing_if = "Option::is_none")]
    pub proration_behavior: Option<models::SubscriptionProrationBehavior>,
    #[serde(
        rename = "cancel_at_period_end",
        skip_serializing_if = "Option::is_none"
    )]
    pub cancel_at_period_end: Option<bool>,
    #[serde(
        rename = "cancellation_reason",
        skip_serializing_if = "Option::is_none"
    )]
    pub cancellation_reason: Option<models::CustomerCancellationReason>,
    #[serde(
        rename = "cancellation_comment",
        skip_serializing_if = "Option::is_none"
    )]
    pub cancellation_comment: Option<String>,
}

impl CustomerSubscriptionUpdate {
    pub fn new(product_id: String, seats: i32) -> CustomerSubscriptionUpdate {
        CustomerSubscriptionUpdate {
            product_id,
            seats,
            proration_behavior: None,
            cancel_at_period_end: None,
            cancellation_reason: None,
            cancellation_comment: None,
        }
    }
}
