/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomerStateSubscriptionMeter : Current consumption and spending for a subscription meter.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerStateSubscriptionMeter {
    /// Creation timestamp of the object.
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "modified_at", deserialize_with = "Option::deserialize")]
    pub modified_at: Option<String>,
    /// The ID of the object.
    #[serde(rename = "id")]
    pub id: String,
    /// The number of consumed units so far in this billing period.
    #[serde(rename = "consumed_units")]
    pub consumed_units: f64,
    /// The number of credited units so far in this billing period.
    #[serde(rename = "credited_units")]
    pub credited_units: i32,
    /// The amount due in cents so far in this billing period.
    #[serde(rename = "amount")]
    pub amount: i32,
    /// The ID of the meter.
    #[serde(rename = "meter_id")]
    pub meter_id: String,
}

impl CustomerStateSubscriptionMeter {
    /// Current consumption and spending for a subscription meter.
    pub fn new(
        created_at: String,
        modified_at: Option<String>,
        id: String,
        consumed_units: f64,
        credited_units: i32,
        amount: i32,
        meter_id: String,
    ) -> CustomerStateSubscriptionMeter {
        CustomerStateSubscriptionMeter {
            created_at,
            modified_at,
            id,
            consumed_units,
            credited_units,
            amount,
            meter_id,
        }
    }
}
