/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerCustomerSession {
    #[serde(rename = "expires_at")]
    pub expires_at: String,
    #[serde(rename = "return_url", deserialize_with = "Option::deserialize")]
    pub return_url: Option<String>,
}

impl CustomerCustomerSession {
    pub fn new(expires_at: String, return_url: Option<String>) -> CustomerCustomerSession {
        CustomerCustomerSession {
            expires_at,
            return_url,
        }
    }
}
