/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerPaymentMethod {
    /// The ID of the object.
    #[serde(rename = "id")]
    pub id: String,
    /// Creation timestamp of the object.
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "modified_at")]
    pub modified_at: String,
    #[serde(rename = "processor")]
    pub processor: models::PaymentProcessor,
    #[serde(rename = "customer_id")]
    pub customer_id: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "method_metadata")]
    pub method_metadata: Box<models::PaymentMethodCardMetadata>,
}

impl CustomerPaymentMethod {
    pub fn new(
        id: String,
        created_at: String,
        modified_at: String,
        processor: models::PaymentProcessor,
        customer_id: String,
        r#type: String,
        method_metadata: models::PaymentMethodCardMetadata,
    ) -> CustomerPaymentMethod {
        CustomerPaymentMethod {
            id,
            created_at,
            modified_at,
            processor,
            customer_id,
            r#type,
            method_metadata: Box::new(method_metadata),
        }
    }
}
