/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerCreatedMetadata {
    #[serde(rename = "customer_id")]
    pub customer_id: String,
    #[serde(rename = "customer_email")]
    pub customer_email: String,
    #[serde(rename = "customer_name", deserialize_with = "Option::deserialize")]
    pub customer_name: Option<String>,
    #[serde(
        rename = "customer_external_id",
        deserialize_with = "Option::deserialize"
    )]
    pub customer_external_id: Option<String>,
}

impl CustomerCreatedMetadata {
    pub fn new(
        customer_id: String,
        customer_email: String,
        customer_name: Option<String>,
        customer_external_id: Option<String>,
    ) -> CustomerCreatedMetadata {
        CustomerCreatedMetadata {
            customer_id,
            customer_email,
            customer_name,
            customer_external_id,
        }
    }
}
