/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerSubscriptionUpdateProduct {
    /// Update subscription to another product.
    #[serde(rename = "product_id")]
    pub product_id: String,
}

impl CustomerSubscriptionUpdateProduct {
    pub fn new(product_id: String) -> CustomerSubscriptionUpdateProduct {
        CustomerSubscriptionUpdateProduct { product_id }
    }
}
