/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerOrderSubscription {
    /// Creation timestamp of the object.
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "modified_at", deserialize_with = "Option::deserialize")]
    pub modified_at: Option<String>,
    /// The ID of the object.
    #[serde(rename = "id")]
    pub id: String,
    /// The amount of the subscription.
    #[serde(rename = "amount")]
    pub amount: i32,
    /// The currency of the subscription.
    #[serde(rename = "currency")]
    pub currency: String,
    /// The interval at which the subscription recurs.
    #[serde(rename = "recurring_interval")]
    pub recurring_interval: models::SubscriptionRecurringInterval,
    /// Number of interval units of the subscription. If this is set to 1 the charge will happen every interval (e.g. every month), if set to 2 it will be every other month, and so on.
    #[serde(rename = "recurring_interval_count")]
    pub recurring_interval_count: i32,
    /// The status of the subscription.
    #[serde(rename = "status")]
    pub status: models::SubscriptionStatus,
    /// The start timestamp of the current billing period.
    #[serde(rename = "current_period_start")]
    pub current_period_start: String,
    #[serde(
        rename = "current_period_end",
        deserialize_with = "Option::deserialize"
    )]
    pub current_period_end: Option<String>,
    #[serde(rename = "trial_start", deserialize_with = "Option::deserialize")]
    pub trial_start: Option<String>,
    #[serde(rename = "trial_end", deserialize_with = "Option::deserialize")]
    pub trial_end: Option<String>,
    /// Whether the subscription will be canceled at the end of the current period.
    #[serde(rename = "cancel_at_period_end")]
    pub cancel_at_period_end: bool,
    #[serde(rename = "canceled_at", deserialize_with = "Option::deserialize")]
    pub canceled_at: Option<String>,
    #[serde(rename = "started_at", deserialize_with = "Option::deserialize")]
    pub started_at: Option<String>,
    #[serde(rename = "ends_at", deserialize_with = "Option::deserialize")]
    pub ends_at: Option<String>,
    #[serde(rename = "ended_at", deserialize_with = "Option::deserialize")]
    pub ended_at: Option<String>,
    /// The ID of the subscribed customer.
    #[serde(rename = "customer_id")]
    pub customer_id: String,
    /// The ID of the subscribed product.
    #[serde(rename = "product_id")]
    pub product_id: String,
    #[serde(rename = "discount_id", deserialize_with = "Option::deserialize")]
    pub discount_id: Option<String>,
    #[serde(rename = "checkout_id", deserialize_with = "Option::deserialize")]
    pub checkout_id: Option<String>,
    #[serde(
        rename = "seats",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub seats: Option<Option<i32>>,
    #[serde(
        rename = "customer_cancellation_reason",
        deserialize_with = "Option::deserialize"
    )]
    pub customer_cancellation_reason: Option<models::CustomerCancellationReason>,
    #[serde(
        rename = "customer_cancellation_comment",
        deserialize_with = "Option::deserialize"
    )]
    pub customer_cancellation_comment: Option<String>,
}

impl CustomerOrderSubscription {
    pub fn new(
        created_at: String,
        modified_at: Option<String>,
        id: String,
        amount: i32,
        currency: String,
        recurring_interval: models::SubscriptionRecurringInterval,
        recurring_interval_count: i32,
        status: models::SubscriptionStatus,
        current_period_start: String,
        current_period_end: Option<String>,
        trial_start: Option<String>,
        trial_end: Option<String>,
        cancel_at_period_end: bool,
        canceled_at: Option<String>,
        started_at: Option<String>,
        ends_at: Option<String>,
        ended_at: Option<String>,
        customer_id: String,
        product_id: String,
        discount_id: Option<String>,
        checkout_id: Option<String>,
        customer_cancellation_reason: Option<models::CustomerCancellationReason>,
        customer_cancellation_comment: Option<String>,
    ) -> CustomerOrderSubscription {
        CustomerOrderSubscription {
            created_at,
            modified_at,
            id,
            amount,
            currency,
            recurring_interval,
            recurring_interval_count,
            status,
            current_period_start,
            current_period_end,
            trial_start,
            trial_end,
            cancel_at_period_end,
            canceled_at,
            started_at,
            ends_at,
            ended_at,
            customer_id,
            product_id,
            discount_id,
            checkout_id,
            seats: None,
            customer_cancellation_reason,
            customer_cancellation_comment,
        }
    }
}
