/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerPaymentMethodCreate {
    #[serde(rename = "confirmation_token_id")]
    pub confirmation_token_id: String,
    #[serde(rename = "set_default")]
    pub set_default: bool,
    #[serde(rename = "return_url")]
    pub return_url: String,
}

impl CustomerPaymentMethodCreate {
    pub fn new(
        confirmation_token_id: String,
        set_default: bool,
        return_url: String,
    ) -> CustomerPaymentMethodCreate {
        CustomerPaymentMethodCreate {
            confirmation_token_id,
            set_default,
            return_url,
        }
    }
}
