/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomFieldCheckbox : Schema for a custom field of type checkbox.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomFieldCheckbox {
    /// Creation timestamp of the object.
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "modified_at", deserialize_with = "Option::deserialize")]
    pub modified_at: Option<String>,
    /// The ID of the object.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "metadata")]
    pub metadata: std::collections::HashMap<String, models::MetadataValue>,
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Identifier of the custom field. It'll be used as key when storing the value.
    #[serde(rename = "slug")]
    pub slug: String,
    /// Name of the custom field.
    #[serde(rename = "name")]
    pub name: String,
    /// The ID of the organization owning the custom field.
    #[serde(rename = "organization_id")]
    pub organization_id: String,
    #[serde(rename = "properties")]
    pub properties: Box<models::CustomFieldCheckboxProperties>,
}

impl CustomFieldCheckbox {
    /// Schema for a custom field of type checkbox.
    pub fn new(
        created_at: String,
        modified_at: Option<String>,
        id: String,
        metadata: std::collections::HashMap<String, models::MetadataValue>,
        r#type: Type,
        slug: String,
        name: String,
        organization_id: String,
        properties: models::CustomFieldCheckboxProperties,
    ) -> CustomFieldCheckbox {
        CustomFieldCheckbox {
            created_at,
            modified_at,
            id,
            metadata,
            r#type,
            slug,
            name,
            organization_id,
            properties: Box::new(properties),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "checkbox")]
    Checkbox,
}

impl Default for Type {
    fn default() -> Type {
        Self::Checkbox
    }
}
