/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomerIdFilter : Filter by customer ID.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerIdFilter {}

impl CustomerIdFilter {
    /// Filter by customer ID.
    pub fn new() -> CustomerIdFilter {
        CustomerIdFilter {}
    }
}
