/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomerOrderPaymentStatus : Payment status for an order.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerOrderPaymentStatus {
    /// Current payment status.
    #[serde(rename = "status")]
    pub status: String,
    #[serde(
        rename = "error",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub error: Option<Option<String>>,
}

impl CustomerOrderPaymentStatus {
    /// Payment status for an order.
    pub fn new(status: String) -> CustomerOrderPaymentStatus {
        CustomerOrderPaymentStatus {
            status,
            error: None,
        }
    }
}
