/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerBenefitGrantDiscordPropertiesUpdate {
    #[serde(rename = "account_id", deserialize_with = "Option::deserialize")]
    pub account_id: Option<String>,
}

impl CustomerBenefitGrantDiscordPropertiesUpdate {
    pub fn new(account_id: Option<String>) -> CustomerBenefitGrantDiscordPropertiesUpdate {
        CustomerBenefitGrantDiscordPropertiesUpdate { account_id }
    }
}
