/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DiscountPercentageOnceForeverDurationCreate : Schema to create a percentage discount that is applied once or forever.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscountPercentageOnceForeverDurationCreate {
    #[serde(rename = "duration")]
    pub duration: models::DiscountDuration,
    /// Type of the discount.
    #[serde(rename = "type")]
    pub r#type: models::DiscountType,
    /// Discount percentage in basis points.  A basis point is 1/100th of a percent. For example, to create a 25.5% discount, set this to 2550.
    #[serde(rename = "basis_points")]
    pub basis_points: i32,
    /// Key-value object allowing you to store additional information.  The key must be a string with a maximum length of **40 characters**. The value must be either:  * A string with a maximum length of **500 characters** * An integer * A floating-point number * A boolean  You can store up to **50 key-value pairs**.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, models::MetadataValue1>>,
    /// Name of the discount. Will be displayed to the customer when the discount is applied.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(
        rename = "code",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub code: Option<Option<String>>,
    #[serde(
        rename = "starts_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub starts_at: Option<Option<String>>,
    #[serde(
        rename = "ends_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub ends_at: Option<Option<String>>,
    #[serde(
        rename = "max_redemptions",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_redemptions: Option<Option<i32>>,
    /// List of product IDs the discount can be applied to.
    #[serde(
        rename = "products",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub products: Option<Option<Vec<String>>>,
    /// The organization ID.
    #[serde(
        rename = "organization_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub organization_id: Option<Option<String>>,
}

impl DiscountPercentageOnceForeverDurationCreate {
    /// Schema to create a percentage discount that is applied once or forever.
    pub fn new(
        duration: models::DiscountDuration,
        r#type: models::DiscountType,
        basis_points: i32,
        name: String,
    ) -> DiscountPercentageOnceForeverDurationCreate {
        DiscountPercentageOnceForeverDurationCreate {
            duration,
            r#type,
            basis_points,
            metadata: None,
            name,
            code: None,
            starts_at: None,
            ends_at: None,
            max_redemptions: None,
            products: None,
            organization_id: None,
        }
    }
}
