/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DiscountFixedOnceForeverDuration : Schema for a fixed amount discount that is applied once or forever.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscountFixedOnceForeverDuration {
    #[serde(rename = "duration")]
    pub duration: models::DiscountDuration,
    #[serde(rename = "type")]
    pub r#type: models::DiscountType,
    #[serde(rename = "amount")]
    pub amount: i32,
    #[serde(rename = "currency")]
    pub currency: String,
    /// Creation timestamp of the object.
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "modified_at", deserialize_with = "Option::deserialize")]
    pub modified_at: Option<String>,
    /// The ID of the object.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "metadata")]
    pub metadata: std::collections::HashMap<String, models::MetadataValue>,
    /// Name of the discount. Will be displayed to the customer when the discount is applied.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "code", deserialize_with = "Option::deserialize")]
    pub code: Option<String>,
    #[serde(rename = "starts_at", deserialize_with = "Option::deserialize")]
    pub starts_at: Option<String>,
    #[serde(rename = "ends_at", deserialize_with = "Option::deserialize")]
    pub ends_at: Option<String>,
    #[serde(rename = "max_redemptions", deserialize_with = "Option::deserialize")]
    pub max_redemptions: Option<i32>,
    /// Number of times the discount has been redeemed.
    #[serde(rename = "redemptions_count")]
    pub redemptions_count: i32,
    /// The organization ID.
    #[serde(rename = "organization_id")]
    pub organization_id: String,
    #[serde(rename = "products")]
    pub products: Vec<models::DiscountProduct>,
}

impl DiscountFixedOnceForeverDuration {
    /// Schema for a fixed amount discount that is applied once or forever.
    pub fn new(
        duration: models::DiscountDuration,
        r#type: models::DiscountType,
        amount: i32,
        currency: String,
        created_at: String,
        modified_at: Option<String>,
        id: String,
        metadata: std::collections::HashMap<String, models::MetadataValue>,
        name: String,
        code: Option<String>,
        starts_at: Option<String>,
        ends_at: Option<String>,
        max_redemptions: Option<i32>,
        redemptions_count: i32,
        organization_id: String,
        products: Vec<models::DiscountProduct>,
    ) -> DiscountFixedOnceForeverDuration {
        DiscountFixedOnceForeverDuration {
            duration,
            r#type,
            amount,
            currency,
            created_at,
            modified_at,
            id,
            metadata,
            name,
            code,
            starts_at,
            ends_at,
            max_redemptions,
            redemptions_count,
            organization_id,
            products,
        }
    }
}
