/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DiscountCreate {
    DiscountFixedOnceForeverDurationCreate(Box<models::DiscountFixedOnceForeverDurationCreate>),
    DiscountFixedRepeatDurationCreate(Box<models::DiscountFixedRepeatDurationCreate>),
    DiscountPercentageOnceForeverDurationCreate(
        Box<models::DiscountPercentageOnceForeverDurationCreate>,
    ),
    DiscountPercentageRepeatDurationCreate(Box<models::DiscountPercentageRepeatDurationCreate>),
}

impl Default for DiscountCreate {
    fn default() -> Self {
        Self::DiscountFixedOnceForeverDurationCreate(Default::default())
    }
}
