/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DownloadableFileCreate : Schema to create a file to be associated with the downloadables benefit.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DownloadableFileCreate {
    /// The organization ID.
    #[serde(
        rename = "organization_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub organization_id: Option<Option<String>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "mime_type")]
    pub mime_type: String,
    #[serde(rename = "size")]
    pub size: i32,
    #[serde(
        rename = "checksum_sha256_base64",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub checksum_sha256_base64: Option<Option<String>>,
    #[serde(rename = "upload")]
    pub upload: Box<models::S3FileCreateMultipart>,
    #[serde(rename = "service")]
    pub service: Service,
    #[serde(
        rename = "version",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub version: Option<Option<String>>,
}

impl DownloadableFileCreate {
    /// Schema to create a file to be associated with the downloadables benefit.
    pub fn new(
        name: String,
        mime_type: String,
        size: i32,
        upload: models::S3FileCreateMultipart,
        service: Service,
    ) -> DownloadableFileCreate {
        DownloadableFileCreate {
            organization_id: None,
            name,
            mime_type,
            size,
            checksum_sha256_base64: None,
            upload: Box::new(upload),
            service,
            version: None,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Service {
    #[serde(rename = "downloadable")]
    Downloadable,
}

impl Default for Service {
    fn default() -> Service {
        Self::Downloadable
    }
}
