/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventCreateExternalCustomer {
    /// The timestamp of the event.
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    /// The name of the event.
    #[serde(rename = "name")]
    pub name: String,
    /// The organization ID.
    #[serde(
        rename = "organization_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub organization_id: Option<Option<String>>,
    /// Key-value object allowing you to store additional information about the event. Some keys like `_llm` are structured data that are handled specially by Polar.  The key must be a string with a maximum length of **40 characters**. The value must be either:  * A string with a maximum length of **500 characters** * An integer * A floating-point number * A boolean  You can store up to **50 key-value pairs**.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<models::EventMetadataInput>,
    /// ID of the customer in your system associated with the event.
    #[serde(rename = "external_customer_id")]
    pub external_customer_id: String,
}

impl EventCreateExternalCustomer {
    pub fn new(name: String, external_customer_id: String) -> EventCreateExternalCustomer {
        EventCreateExternalCustomer {
            timestamp: None,
            name,
            organization_id: None,
            metadata: None,
            external_customer_id,
        }
    }
}
