/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventMetadataOutput {
    #[serde(rename = "_cost", skip_serializing_if = "Option::is_none")]
    pub _cost: Option<Box<models::CostMetadataOutput>>,
    #[serde(rename = "_llm", skip_serializing_if = "Option::is_none")]
    pub _llm: Option<Box<models::LlmMetadata>>,
}

impl EventMetadataOutput {
    pub fn new() -> EventMetadataOutput {
        EventMetadataOutput {
            _cost: None,
            _llm: None,
        }
    }
}
