/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventsIngest {
    /// List of events to ingest.
    #[serde(rename = "events")]
    pub events: Vec<models::EventsIngestEventsInner>,
}

impl EventsIngest {
    pub fn new(events: Vec<models::EventsIngestEventsInner>) -> EventsIngest {
        EventsIngest { events }
    }
}
