/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "source")]
pub enum Event {
    #[serde(rename = "system")]
    System(Box<models::SystemEvent>),
    #[serde(rename = "user")]
    User(Box<models::UserEvent>),
}

impl Default for Event {
    fn default() -> Self {
        Self::System(Default::default())
    }
}
