/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExistingProductPrice : A price that already exists for this product.  Useful when updating a product if you want to keep an existing price.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExistingProductPrice {
    #[serde(rename = "id")]
    pub id: String,
}

impl ExistingProductPrice {
    /// A price that already exists for this product.  Useful when updating a product if you want to keep an existing price.
    pub fn new(id: String) -> ExistingProductPrice {
        ExistingProductPrice { id }
    }
}
