/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExternalCustomerIdFilter : Filter by customer external ID.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExternalCustomerIdFilter {}

impl ExternalCustomerIdFilter {
    /// Filter by customer external ID.
    pub fn new() -> ExternalCustomerIdFilter {
        ExternalCustomerIdFilter {}
    }
}
