/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LicenseKeyValidate {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "organization_id")]
    pub organization_id: String,
    #[serde(
        rename = "activation_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub activation_id: Option<Option<String>>,
    /// The benefit ID.
    #[serde(
        rename = "benefit_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub benefit_id: Option<Option<String>>,
    #[serde(
        rename = "customer_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub customer_id: Option<Option<String>>,
    #[serde(
        rename = "increment_usage",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub increment_usage: Option<Option<i32>>,
    /// Key-value object allowing you to set conditions that must match when validating the license key.  The key must be a string with a maximum length of **40 characters**. The value must be either:  * A string with a maximum length of **500 characters** * An integer * A floating-point number * A boolean  You can store up to **50 key-value pairs**.
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<std::collections::HashMap<String, models::MetadataValue1>>,
}

impl LicenseKeyValidate {
    pub fn new(key: String, organization_id: String) -> LicenseKeyValidate {
        LicenseKeyValidate {
            key,
            organization_id,
            activation_id: None,
            benefit_id: None,
            customer_id: None,
            increment_usage: None,
            conditions: None,
        }
    }
}
