/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LicenseKeyDeactivate {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "organization_id")]
    pub organization_id: String,
    #[serde(rename = "activation_id")]
    pub activation_id: String,
}

impl LicenseKeyDeactivate {
    pub fn new(
        key: String,
        organization_id: String,
        activation_id: String,
    ) -> LicenseKeyDeactivate {
        LicenseKeyDeactivate {
            key,
            organization_id,
            activation_id,
        }
    }
}
