/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LicenseKeyUser {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "public_name")]
    pub public_name: String,
    #[serde(
        rename = "avatar_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub avatar_url: Option<Option<String>>,
}

impl LicenseKeyUser {
    pub fn new(id: String, email: String, public_name: String) -> LicenseKeyUser {
        LicenseKeyUser {
            id,
            email,
            public_name,
            avatar_url: None,
        }
    }
}
