/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListResourceEventName {
    #[serde(rename = "items")]
    pub items: Vec<models::EventName>,
    #[serde(rename = "pagination")]
    pub pagination: Box<models::Pagination>,
}

impl ListResourceEventName {
    pub fn new(
        items: Vec<models::EventName>,
        pagination: models::Pagination,
    ) -> ListResourceEventName {
        ListResourceEventName {
            items,
            pagination: Box::new(pagination),
        }
    }
}
