/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListResourceMeter {
    #[serde(rename = "items")]
    pub items: Vec<models::Meter>,
    #[serde(rename = "pagination")]
    pub pagination: Box<models::Pagination>,
}

impl ListResourceMeter {
    pub fn new(items: Vec<models::Meter>, pagination: models::Pagination) -> ListResourceMeter {
        ListResourceMeter {
            items,
            pagination: Box::new(pagination),
        }
    }
}
