/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LlmMetadata {
    /// The vendor of the event.
    #[serde(rename = "vendor")]
    pub vendor: String,
    /// The model used for the event.
    #[serde(rename = "model")]
    pub model: String,
    #[serde(
        rename = "prompt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub prompt: Option<Option<String>>,
    #[serde(
        rename = "response",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub response: Option<Option<String>>,
    /// The number of LLM input tokens used for the event.
    #[serde(rename = "input_tokens")]
    pub input_tokens: i32,
    /// The number of LLM cached tokens that were used for the event.
    #[serde(
        rename = "cached_input_tokens",
        skip_serializing_if = "Option::is_none"
    )]
    pub cached_input_tokens: Option<i32>,
    /// The number of LLM output tokens used for the event.
    #[serde(rename = "output_tokens")]
    pub output_tokens: i32,
    /// The total number of LLM tokens used for the event.
    #[serde(rename = "total_tokens")]
    pub total_tokens: i32,
}

impl LlmMetadata {
    pub fn new(
        vendor: String,
        model: String,
        input_tokens: i32,
        output_tokens: i32,
        total_tokens: i32,
    ) -> LlmMetadata {
        LlmMetadata {
            vendor,
            model,
            prompt: None,
            response: None,
            input_tokens,
            cached_input_tokens: None,
            output_tokens,
            total_tokens,
        }
    }
}
