/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeterCreate {
    /// Key-value object allowing you to store additional information.  The key must be a string with a maximum length of **40 characters**. The value must be either:  * A string with a maximum length of **500 characters** * An integer * A floating-point number * A boolean  You can store up to **50 key-value pairs**.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, models::MetadataValue1>>,
    /// The name of the meter. Will be shown on customer's invoices and usage.
    #[serde(rename = "name")]
    pub name: String,
    /// The filter to apply on events that'll be used to calculate the meter.
    #[serde(rename = "filter")]
    pub filter: Box<models::Filter>,
    #[serde(rename = "aggregation")]
    pub aggregation: Box<models::Aggregation>,
    /// The organization ID.
    #[serde(
        rename = "organization_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub organization_id: Option<Option<String>>,
}

impl MeterCreate {
    pub fn new(
        name: String,
        filter: models::Filter,
        aggregation: models::Aggregation,
    ) -> MeterCreate {
        MeterCreate {
            metadata: None,
            name,
            filter: Box::new(filter),
            aggregation: Box::new(aggregation),
            organization_id: None,
        }
    }
}
