/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeterCreditedMetadata {
    #[serde(rename = "meter_id")]
    pub meter_id: String,
    #[serde(rename = "units")]
    pub units: i32,
    #[serde(rename = "rollover")]
    pub rollover: bool,
}

impl MeterCreditedMetadata {
    pub fn new(meter_id: String, units: i32, rollover: bool) -> MeterCreditedMetadata {
        MeterCreditedMetadata {
            meter_id,
            units,
            rollover,
        }
    }
}
