/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeterQuantities {
    #[serde(rename = "quantities")]
    pub quantities: Vec<models::MeterQuantity>,
    /// The total quantity for the period.
    #[serde(rename = "total")]
    pub total: f64,
}

impl MeterQuantities {
    pub fn new(quantities: Vec<models::MeterQuantity>, total: f64) -> MeterQuantities {
        MeterQuantities { quantities, total }
    }
}
