/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MeterSortProperty {
    #[serde(rename = "created_at")]
    CreatedAt,
    #[serde(rename = "-created_at")]
    CreatedAt2,
    #[serde(rename = "name")]
    Name,
    #[serde(rename = "-name")]
    Name2,
}

impl std::fmt::Display for MeterSortProperty {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CreatedAt => write!(f, "created_at"),
            Self::CreatedAt2 => write!(f, "-created_at"),
            Self::Name => write!(f, "name"),
            Self::Name2 => write!(f, "-name"),
        }
    }
}

impl Default for MeterSortProperty {
    fn default() -> MeterSortProperty {
        Self::CreatedAt
    }
}
