/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MethodFilter : Filter by payment method.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MethodFilter {}

impl MethodFilter {
    /// Filter by payment method.
    pub fn new() -> MethodFilter {
        MethodFilter {}
    }
}
