/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MetricsIntervalLimit : Date interval limit to get metrics for a given interval.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MetricsIntervalLimit {
    /// Maximum number of days for this interval.
    #[serde(rename = "max_days")]
    pub max_days: i32,
}

impl MetricsIntervalLimit {
    /// Date interval limit to get metrics for a given interval.
    pub fn new(max_days: i32) -> MetricsIntervalLimit {
        MetricsIntervalLimit { max_days }
    }
}
