/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuth2ClientPublic {
    /// Creation timestamp of the object.
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "modified_at", deserialize_with = "Option::deserialize")]
    pub modified_at: Option<String>,
    #[serde(rename = "client_id")]
    pub client_id: String,
    #[serde(rename = "client_name", deserialize_with = "Option::deserialize")]
    pub client_name: Option<String>,
    #[serde(rename = "client_uri", deserialize_with = "Option::deserialize")]
    pub client_uri: Option<String>,
    #[serde(rename = "logo_uri", deserialize_with = "Option::deserialize")]
    pub logo_uri: Option<String>,
    #[serde(rename = "tos_uri", deserialize_with = "Option::deserialize")]
    pub tos_uri: Option<String>,
    #[serde(rename = "policy_uri", deserialize_with = "Option::deserialize")]
    pub policy_uri: Option<String>,
}

impl OAuth2ClientPublic {
    pub fn new(
        created_at: String,
        modified_at: Option<String>,
        client_id: String,
        client_name: Option<String>,
        client_uri: Option<String>,
        logo_uri: Option<String>,
        tos_uri: Option<String>,
        policy_uri: Option<String>,
    ) -> OAuth2ClientPublic {
        OAuth2ClientPublic {
            created_at,
            modified_at,
            client_id,
            client_name,
            client_uri,
            logo_uri,
            tos_uri,
            policy_uri,
        }
    }
}
