/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderPaidMetadata {
    #[serde(rename = "order_id")]
    pub order_id: String,
    #[serde(rename = "amount")]
    pub amount: i32,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "backfilled", skip_serializing_if = "Option::is_none")]
    pub backfilled: Option<bool>,
}

impl OrderPaidMetadata {
    pub fn new(order_id: String, amount: i32, currency: String) -> OrderPaidMetadata {
        OrderPaidMetadata {
            order_id,
            amount,
            currency,
            backfilled: None,
        }
    }
}
