/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Order {
    /// The ID of the object.
    #[serde(rename = "id")]
    pub id: String,
    /// Creation timestamp of the object.
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "modified_at", deserialize_with = "Option::deserialize")]
    pub modified_at: Option<String>,
    #[serde(rename = "status")]
    pub status: models::OrderStatus,
    /// Whether the order has been paid for.
    #[serde(rename = "paid")]
    pub paid: bool,
    /// Amount in cents, before discounts and taxes.
    #[serde(rename = "subtotal_amount")]
    pub subtotal_amount: i32,
    /// Discount amount in cents.
    #[serde(rename = "discount_amount")]
    pub discount_amount: i32,
    /// Amount in cents, after discounts but before taxes.
    #[serde(rename = "net_amount")]
    pub net_amount: i32,
    /// Sales tax amount in cents.
    #[serde(rename = "tax_amount")]
    pub tax_amount: i32,
    /// Amount in cents, after discounts and taxes.
    #[serde(rename = "total_amount")]
    pub total_amount: i32,
    /// Customer's balance amount applied to this invoice. Can increase the total amount paid, if the customer has a negative balance,  or decrease it, if the customer has a positive balance.Amount in cents.
    #[serde(rename = "applied_balance_amount")]
    pub applied_balance_amount: i32,
    /// Amount in cents that is due for this order.
    #[serde(rename = "due_amount")]
    pub due_amount: i32,
    /// Amount refunded in cents.
    #[serde(rename = "refunded_amount")]
    pub refunded_amount: i32,
    /// Sales tax refunded in cents.
    #[serde(rename = "refunded_tax_amount")]
    pub refunded_tax_amount: i32,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "billing_reason")]
    pub billing_reason: models::OrderBillingReason,
    #[serde(rename = "billing_name", deserialize_with = "Option::deserialize")]
    pub billing_name: Option<String>,
    #[serde(rename = "billing_address", deserialize_with = "Option::deserialize")]
    pub billing_address: Option<Box<models::Address>>,
    /// The invoice number associated with this order.
    #[serde(rename = "invoice_number")]
    pub invoice_number: String,
    /// Whether an invoice has been generated for this order.
    #[serde(rename = "is_invoice_generated")]
    pub is_invoice_generated: bool,
    #[serde(
        rename = "seats",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub seats: Option<Option<i32>>,
    #[serde(rename = "customer_id")]
    pub customer_id: String,
    #[serde(rename = "product_id", deserialize_with = "Option::deserialize")]
    pub product_id: Option<String>,
    #[serde(rename = "discount_id", deserialize_with = "Option::deserialize")]
    pub discount_id: Option<String>,
    #[serde(rename = "subscription_id", deserialize_with = "Option::deserialize")]
    pub subscription_id: Option<String>,
    #[serde(rename = "checkout_id", deserialize_with = "Option::deserialize")]
    pub checkout_id: Option<String>,
    #[serde(rename = "metadata")]
    pub metadata: std::collections::HashMap<String, models::MetadataValue>,
    /// Key-value object storing custom field values.
    #[serde(rename = "custom_field_data", skip_serializing_if = "Option::is_none")]
    pub custom_field_data: Option<std::collections::HashMap<String, models::CustomFieldDataValue>>,
    /// Platform fee amount in cents.
    #[serde(rename = "platform_fee_amount")]
    pub platform_fee_amount: i32,
    #[serde(rename = "customer")]
    pub customer: Box<models::OrderCustomer>,
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "product", deserialize_with = "Option::deserialize")]
    pub product: Option<Box<models::OrderProduct>>,
    #[serde(rename = "discount", deserialize_with = "Option::deserialize")]
    pub discount: Option<Box<models::OrderDiscount>>,
    #[serde(rename = "subscription", deserialize_with = "Option::deserialize")]
    pub subscription: Option<Box<models::OrderSubscription>>,
    /// Line items composing the order.
    #[serde(rename = "items")]
    pub items: Vec<models::OrderItemSchema>,
    /// A summary description of the order.
    #[serde(rename = "description")]
    pub description: String,
}

impl Order {
    pub fn new(
        id: String,
        created_at: String,
        modified_at: Option<String>,
        status: models::OrderStatus,
        paid: bool,
        subtotal_amount: i32,
        discount_amount: i32,
        net_amount: i32,
        tax_amount: i32,
        total_amount: i32,
        applied_balance_amount: i32,
        due_amount: i32,
        refunded_amount: i32,
        refunded_tax_amount: i32,
        currency: String,
        billing_reason: models::OrderBillingReason,
        billing_name: Option<String>,
        billing_address: Option<models::Address>,
        invoice_number: String,
        is_invoice_generated: bool,
        customer_id: String,
        product_id: Option<String>,
        discount_id: Option<String>,
        subscription_id: Option<String>,
        checkout_id: Option<String>,
        metadata: std::collections::HashMap<String, models::MetadataValue>,
        platform_fee_amount: i32,
        customer: models::OrderCustomer,
        user_id: String,
        product: Option<models::OrderProduct>,
        discount: Option<models::OrderDiscount>,
        subscription: Option<models::OrderSubscription>,
        items: Vec<models::OrderItemSchema>,
        description: String,
    ) -> Order {
        Order {
            id,
            created_at,
            modified_at,
            status,
            paid,
            subtotal_amount,
            discount_amount,
            net_amount,
            tax_amount,
            total_amount,
            applied_balance_amount,
            due_amount,
            refunded_amount,
            refunded_tax_amount,
            currency,
            billing_reason,
            billing_name,
            billing_address: billing_address.map(Box::new),
            invoice_number,
            is_invoice_generated,
            seats: None,
            customer_id,
            product_id,
            discount_id,
            subscription_id,
            checkout_id,
            metadata,
            custom_field_data: None,
            platform_fee_amount,
            customer: Box::new(customer),
            user_id,
            product: product.map(Box::new),
            discount: discount.map(Box::new),
            subscription: subscription.map(Box::new),
            items,
            description,
        }
    }
}
