/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderInvoice : Order's invoice data.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderInvoice {
    /// The URL to the invoice.
    #[serde(rename = "url")]
    pub url: String,
}

impl OrderInvoice {
    /// Order's invoice data.
    pub fn new(url: String) -> OrderInvoice {
        OrderInvoice { url }
    }
}
