/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationSubscribePromoteSettings {
    /// Promote email subscription (free)
    #[serde(rename = "promote", skip_serializing_if = "Option::is_none")]
    pub promote: Option<bool>,
    /// Show subscription count publicly
    #[serde(rename = "show_count", skip_serializing_if = "Option::is_none")]
    pub show_count: Option<bool>,
    /// Include free subscribers in total count
    #[serde(rename = "count_free", skip_serializing_if = "Option::is_none")]
    pub count_free: Option<bool>,
}

impl OrganizationSubscribePromoteSettings {
    pub fn new() -> OrganizationSubscribePromoteSettings {
        OrganizationSubscribePromoteSettings {
            promote: None,
            show_count: None,
            count_free: None,
        }
    }
}
