/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationCustomerEmailSettings {
    #[serde(rename = "order_confirmation")]
    pub order_confirmation: bool,
    #[serde(rename = "subscription_cancellation")]
    pub subscription_cancellation: bool,
    #[serde(rename = "subscription_confirmation")]
    pub subscription_confirmation: bool,
    #[serde(rename = "subscription_cycled")]
    pub subscription_cycled: bool,
    #[serde(rename = "subscription_past_due")]
    pub subscription_past_due: bool,
    #[serde(rename = "subscription_revoked")]
    pub subscription_revoked: bool,
    #[serde(rename = "subscription_uncanceled")]
    pub subscription_uncanceled: bool,
    #[serde(rename = "subscription_updated")]
    pub subscription_updated: bool,
}

impl OrganizationCustomerEmailSettings {
    pub fn new(
        order_confirmation: bool,
        subscription_cancellation: bool,
        subscription_confirmation: bool,
        subscription_cycled: bool,
        subscription_past_due: bool,
        subscription_revoked: bool,
        subscription_uncanceled: bool,
        subscription_updated: bool,
    ) -> OrganizationCustomerEmailSettings {
        OrganizationCustomerEmailSettings {
            order_confirmation,
            subscription_cancellation,
            subscription_confirmation,
            subscription_cycled,
            subscription_past_due,
            subscription_revoked,
            subscription_uncanceled,
            subscription_updated,
        }
    }
}
