/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProductPriceFixed : A fixed price for a product.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductPriceFixed {
    /// Creation timestamp of the object.
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "modified_at", deserialize_with = "Option::deserialize")]
    pub modified_at: Option<String>,
    /// The ID of the price.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "amount_type")]
    pub amount_type: AmountType,
    /// Whether the price is archived and no longer available.
    #[serde(rename = "is_archived")]
    pub is_archived: bool,
    /// The ID of the product owning the price.
    #[serde(rename = "product_id")]
    pub product_id: String,
    #[serde(rename = "type")]
    pub r#type: models::ProductPriceType,
    #[serde(
        rename = "recurring_interval",
        deserialize_with = "Option::deserialize"
    )]
    pub recurring_interval: Option<models::SubscriptionRecurringInterval>,
    /// The currency.
    #[serde(rename = "price_currency")]
    pub price_currency: String,
    /// The price in cents.
    #[serde(rename = "price_amount")]
    pub price_amount: i32,
}

impl ProductPriceFixed {
    /// A fixed price for a product.
    pub fn new(
        created_at: String,
        modified_at: Option<String>,
        id: String,
        amount_type: AmountType,
        is_archived: bool,
        product_id: String,
        r#type: models::ProductPriceType,
        recurring_interval: Option<models::SubscriptionRecurringInterval>,
        price_currency: String,
        price_amount: i32,
    ) -> ProductPriceFixed {
        ProductPriceFixed {
            created_at,
            modified_at,
            id,
            amount_type,
            is_archived,
            product_id,
            r#type,
            recurring_interval,
            price_currency,
            price_amount,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AmountType {
    #[serde(rename = "fixed")]
    Fixed,
}

impl Default for AmountType {
    fn default() -> AmountType {
        Self::Fixed
    }
}
