/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProductPriceFixedCreate : Schema to create a fixed price.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductPriceFixedCreate {
    #[serde(rename = "amount_type")]
    pub amount_type: AmountType,
    /// The price in cents.
    #[serde(rename = "price_amount")]
    pub price_amount: i32,
    /// The currency. Currently, only `usd` is supported.
    #[serde(rename = "price_currency", skip_serializing_if = "Option::is_none")]
    pub price_currency: Option<String>,
}

impl ProductPriceFixedCreate {
    /// Schema to create a fixed price.
    pub fn new(amount_type: AmountType, price_amount: i32) -> ProductPriceFixedCreate {
        ProductPriceFixedCreate {
            amount_type,
            price_amount,
            price_currency: None,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AmountType {
    #[serde(rename = "fixed")]
    Fixed,
}

impl Default for AmountType {
    fn default() -> AmountType {
        Self::Fixed
    }
}
