/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductCreateOneTime {
    /// Key-value object allowing you to store additional information.  The key must be a string with a maximum length of **40 characters**. The value must be either:  * A string with a maximum length of **500 characters** * An integer * A floating-point number * A boolean  You can store up to **50 key-value pairs**.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, models::MetadataValue1>>,
    /// The name of the product.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// List of available prices for this product. It should contain at most one static price (fixed, custom or free), and any number of metered prices. Metered prices are not supported on one-time purchase products.
    #[serde(rename = "prices")]
    pub prices: Vec<models::ProductCreateOneTimePricesInner>,
    #[serde(
        rename = "medias",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub medias: Option<Option<Vec<String>>>,
    /// List of custom fields to attach.
    #[serde(
        rename = "attached_custom_fields",
        skip_serializing_if = "Option::is_none"
    )]
    pub attached_custom_fields: Option<Vec<models::AttachedCustomFieldCreate>>,
    /// The organization ID.
    #[serde(
        rename = "organization_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub organization_id: Option<Option<String>>,
    /// States that the product is a one-time purchase.
    #[serde(rename = "recurring_interval", skip_serializing_if = "Option::is_none")]
    pub recurring_interval: Option<models::Null>,
    /// One-time products don't have a recurring interval count.
    #[serde(
        rename = "recurring_interval_count",
        skip_serializing_if = "Option::is_none"
    )]
    pub recurring_interval_count: Option<models::Null>,
}

impl ProductCreateOneTime {
    pub fn new(
        name: String,
        prices: Vec<models::ProductCreateOneTimePricesInner>,
    ) -> ProductCreateOneTime {
        ProductCreateOneTime {
            metadata: None,
            name,
            description: None,
            prices,
            medias: None,
            attached_custom_fields: None,
            organization_id: None,
            recurring_interval: None,
            recurring_interval_count: None,
        }
    }
}
