/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProductPriceSeatTiers : List of pricing tiers for seat-based pricing.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductPriceSeatTiers {
    /// List of pricing tiers
    #[serde(rename = "tiers")]
    pub tiers: Vec<models::ProductPriceSeatTier>,
}

impl ProductPriceSeatTiers {
    /// List of pricing tiers for seat-based pricing.
    pub fn new(tiers: Vec<models::ProductPriceSeatTier>) -> ProductPriceSeatTiers {
        ProductPriceSeatTiers { tiers }
    }
}
