/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductCreateRecurring {
    /// Key-value object allowing you to store additional information.  The key must be a string with a maximum length of **40 characters**. The value must be either:  * A string with a maximum length of **500 characters** * An integer * A floating-point number * A boolean  You can store up to **50 key-value pairs**.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, models::MetadataValue1>>,
    /// The name of the product.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// List of available prices for this product. It should contain at most one static price (fixed, custom or free), and any number of metered prices. Metered prices are not supported on one-time purchase products.
    #[serde(rename = "prices")]
    pub prices: Vec<models::ProductCreateOneTimePricesInner>,
    #[serde(
        rename = "medias",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub medias: Option<Option<Vec<String>>>,
    /// List of custom fields to attach.
    #[serde(
        rename = "attached_custom_fields",
        skip_serializing_if = "Option::is_none"
    )]
    pub attached_custom_fields: Option<Vec<models::AttachedCustomFieldCreate>>,
    /// The organization ID.
    #[serde(
        rename = "organization_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub organization_id: Option<Option<String>>,
    #[serde(
        rename = "trial_interval",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub trial_interval: Option<Option<models::TrialInterval>>,
    #[serde(
        rename = "trial_interval_count",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub trial_interval_count: Option<Option<i32>>,
    /// The recurring interval of the product. Note that the `day` and `week` values are for internal Polar staff use only.
    #[serde(rename = "recurring_interval")]
    pub recurring_interval: models::SubscriptionRecurringInterval,
    /// Number of interval units of the subscription. If this is set to 1 the charge will happen every interval (e.g. every month), if set to 2 it will be every other month, and so on.
    #[serde(
        rename = "recurring_interval_count",
        skip_serializing_if = "Option::is_none"
    )]
    pub recurring_interval_count: Option<i32>,
}

impl ProductCreateRecurring {
    pub fn new(
        name: String,
        prices: Vec<models::ProductCreateOneTimePricesInner>,
        recurring_interval: models::SubscriptionRecurringInterval,
    ) -> ProductCreateRecurring {
        ProductCreateRecurring {
            metadata: None,
            name,
            description: None,
            prices,
            medias: None,
            attached_custom_fields: None,
            organization_id: None,
            trial_interval: None,
            trial_interval_count: None,
            recurring_interval,
            recurring_interval_count: None,
        }
    }
}
