/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProductBillingTypeFilter : Filter by product billing type. `recurring` will filter data corresponding to subscriptions creations or renewals. `one_time` will filter data corresponding to one-time purchases.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductBillingTypeFilter {}

impl ProductBillingTypeFilter {
    /// Filter by product billing type. `recurring` will filter data corresponding to subscriptions creations or renewals. `one_time` will filter data corresponding to one-time purchases.
    pub fn new() -> ProductBillingTypeFilter {
        ProductBillingTypeFilter {}
    }
}
