/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProductBenefitsUpdate : Schema to update the benefits granted by a product.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductBenefitsUpdate {
    /// List of benefit IDs. Each one must be on the same organization as the product.
    #[serde(rename = "benefits")]
    pub benefits: Vec<String>,
}

impl ProductBenefitsUpdate {
    /// Schema to update the benefits granted by a product.
    pub fn new(benefits: Vec<String>) -> ProductBenefitsUpdate {
        ProductBenefitsUpdate { benefits }
    }
}
