/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProductPriceMeter : A meter associated to a metered price.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductPriceMeter {
    /// The ID of the object.
    #[serde(rename = "id")]
    pub id: String,
    /// The name of the meter.
    #[serde(rename = "name")]
    pub name: String,
}

impl ProductPriceMeter {
    /// A meter associated to a metered price.
    pub fn new(id: String, name: String) -> ProductPriceMeter {
        ProductPriceMeter { id, name }
    }
}
