/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "amount_type")]
pub enum ProductPrice {
    #[serde(rename = "fixed")]
    Fixed(Box<models::ProductPriceFixed>),
    #[serde(rename = "custom")]
    Custom(Box<models::ProductPriceCustom>),
    #[serde(rename = "free")]
    Free(Box<models::ProductPriceFree>),
    #[serde(rename = "seat_based")]
    SeatBased(Box<models::ProductPriceSeatBased>),
    #[serde(rename = "metered_unit")]
    MeteredUnit(Box<models::ProductPriceMeteredUnit>),
}

impl Default for ProductPrice {
    fn default() -> Self {
        Self::Fixed(Default::default())
    }
}
