/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RefundReason {
    #[serde(rename = "duplicate")]
    Duplicate,
    #[serde(rename = "fraudulent")]
    Fraudulent,
    #[serde(rename = "customer_request")]
    CustomerRequest,
    #[serde(rename = "service_disruption")]
    ServiceDisruption,
    #[serde(rename = "satisfaction_guarantee")]
    SatisfactionGuarantee,
    #[serde(rename = "other")]
    Other,
}

impl std::fmt::Display for RefundReason {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Duplicate => write!(f, "duplicate"),
            Self::Fraudulent => write!(f, "fraudulent"),
            Self::CustomerRequest => write!(f, "customer_request"),
            Self::ServiceDisruption => write!(f, "service_disruption"),
            Self::SatisfactionGuarantee => write!(f, "satisfaction_guarantee"),
            Self::Other => write!(f, "other"),
        }
    }
}

impl Default for RefundReason {
    fn default() -> RefundReason {
        Self::Duplicate
    }
}
