/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "service")]
pub enum ResponseFilesUpdate {
    #[serde(rename = "downloadable")]
    Downloadable(Box<models::DownloadableFileRead>),
    #[serde(rename = "product_media")]
    ProductMedia(Box<models::ProductMediaFileRead>),
    #[serde(rename = "organization_avatar")]
    OrganizationAvatar(Box<models::OrganizationAvatarFileRead>),
}

impl Default for ResponseFilesUpdate {
    fn default() -> Self {
        Self::Downloadable(Default::default())
    }
}
