/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct S3FileUploadCompletedPart {
    #[serde(rename = "number")]
    pub number: i32,
    #[serde(rename = "checksum_etag")]
    pub checksum_etag: String,
    #[serde(
        rename = "checksum_sha256_base64",
        deserialize_with = "Option::deserialize"
    )]
    pub checksum_sha256_base64: Option<String>,
}

impl S3FileUploadCompletedPart {
    pub fn new(
        number: i32,
        checksum_etag: String,
        checksum_sha256_base64: Option<String>,
    ) -> S3FileUploadCompletedPart {
        S3FileUploadCompletedPart {
            number,
            checksum_etag,
            checksum_sha256_base64,
        }
    }
}
