/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct S3FileUploadPart {
    #[serde(rename = "number")]
    pub number: i32,
    #[serde(rename = "chunk_start")]
    pub chunk_start: i32,
    #[serde(rename = "chunk_end")]
    pub chunk_end: i32,
    #[serde(
        rename = "checksum_sha256_base64",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub checksum_sha256_base64: Option<Option<String>>,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "expires_at")]
    pub expires_at: String,
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<std::collections::HashMap<String, String>>,
}

impl S3FileUploadPart {
    pub fn new(
        number: i32,
        chunk_start: i32,
        chunk_end: i32,
        url: String,
        expires_at: String,
    ) -> S3FileUploadPart {
        S3FileUploadPart {
            number,
            chunk_start,
            chunk_end,
            checksum_sha256_base64: None,
            url,
            expires_at,
            headers: None,
        }
    }
}
