/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SeatsList {
    /// List of seats
    #[serde(rename = "seats")]
    pub seats: Vec<models::CustomerSeat>,
    /// Number of available seats
    #[serde(rename = "available_seats")]
    pub available_seats: i32,
    /// Total number of seats for the subscription
    #[serde(rename = "total_seats")]
    pub total_seats: i32,
}

impl SeatsList {
    pub fn new(
        seats: Vec<models::CustomerSeat>,
        available_seats: i32,
        total_seats: i32,
    ) -> SeatsList {
        SeatsList {
            seats,
            available_seats,
            total_seats,
        }
    }
}
