/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StatusFilter : Filter by checkout session status.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusFilter {}

impl StatusFilter {
    /// Filter by checkout session status.
    pub fn new() -> StatusFilter {
        StatusFilter {}
    }
}
