/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionCycledMetadata {
    #[serde(rename = "subscription_id")]
    pub subscription_id: String,
}

impl SubscriptionCycledMetadata {
    pub fn new(subscription_id: String) -> SubscriptionCycledMetadata {
        SubscriptionCycledMetadata { subscription_id }
    }
}
