/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionUpdateTrial {
    #[serde(rename = "trial_end")]
    pub trial_end: Box<models::TrialEnd>,
}

impl SubscriptionUpdateTrial {
    pub fn new(trial_end: models::TrialEnd) -> SubscriptionUpdateTrial {
        SubscriptionUpdateTrial {
            trial_end: Box::new(trial_end),
        }
    }
}
