/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SubscriptionSortProperty {
    #[serde(rename = "customer")]
    Customer,
    #[serde(rename = "-customer")]
    Customer2,
    #[serde(rename = "status")]
    Status,
    #[serde(rename = "-status")]
    Status2,
    #[serde(rename = "started_at")]
    StartedAt,
    #[serde(rename = "-started_at")]
    StartedAt2,
    #[serde(rename = "current_period_end")]
    CurrentPeriodEnd,
    #[serde(rename = "-current_period_end")]
    CurrentPeriodEnd2,
    #[serde(rename = "amount")]
    Amount,
    #[serde(rename = "-amount")]
    Amount2,
    #[serde(rename = "product")]
    Product,
    #[serde(rename = "-product")]
    Product2,
    #[serde(rename = "discount")]
    Discount,
    #[serde(rename = "-discount")]
    Discount2,
}

impl std::fmt::Display for SubscriptionSortProperty {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Customer => write!(f, "customer"),
            Self::Customer2 => write!(f, "-customer"),
            Self::Status => write!(f, "status"),
            Self::Status2 => write!(f, "-status"),
            Self::StartedAt => write!(f, "started_at"),
            Self::StartedAt2 => write!(f, "-started_at"),
            Self::CurrentPeriodEnd => write!(f, "current_period_end"),
            Self::CurrentPeriodEnd2 => write!(f, "-current_period_end"),
            Self::Amount => write!(f, "amount"),
            Self::Amount2 => write!(f, "-amount"),
            Self::Product => write!(f, "product"),
            Self::Product2 => write!(f, "-product"),
            Self::Discount => write!(f, "discount"),
            Self::Discount2 => write!(f, "-discount"),
        }
    }
}

impl Default for SubscriptionSortProperty {
    fn default() -> SubscriptionSortProperty {
        Self::Customer
    }
}
