/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionRevoke {
    #[serde(
        rename = "customer_cancellation_reason",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub customer_cancellation_reason: Option<Option<models::CustomerCancellationReason>>,
    #[serde(
        rename = "customer_cancellation_comment",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub customer_cancellation_comment: Option<Option<String>>,
    /// Cancel and revoke an active subscription immediately
    #[serde(rename = "revoke")]
    pub revoke: Revoke,
}

impl SubscriptionRevoke {
    pub fn new(revoke: Revoke) -> SubscriptionRevoke {
        SubscriptionRevoke {
            customer_cancellation_reason: None,
            customer_cancellation_comment: None,
            revoke,
        }
    }
}
/// Cancel and revoke an active subscription immediately
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Revoke {
    #[serde(rename = "true")]
    True,
}

impl Default for Revoke {
    fn default() -> Revoke {
        Self::True
    }
}
