/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionCancel {
    #[serde(
        rename = "customer_cancellation_reason",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub customer_cancellation_reason: Option<Option<models::CustomerCancellationReason>>,
    #[serde(
        rename = "customer_cancellation_comment",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub customer_cancellation_comment: Option<Option<String>>,
    /// Cancel an active subscription once the current period ends.  Or uncancel a subscription currently set to be revoked at period end.
    #[serde(rename = "cancel_at_period_end")]
    pub cancel_at_period_end: bool,
}

impl SubscriptionCancel {
    pub fn new(cancel_at_period_end: bool) -> SubscriptionCancel {
        SubscriptionCancel {
            customer_cancellation_reason: None,
            customer_cancellation_comment: None,
            cancel_at_period_end,
        }
    }
}
