/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionProductUpdatedMetadata {
    #[serde(rename = "subscription_id")]
    pub subscription_id: String,
    #[serde(rename = "old_product_id")]
    pub old_product_id: String,
    #[serde(rename = "new_product_id")]
    pub new_product_id: String,
}

impl SubscriptionProductUpdatedMetadata {
    pub fn new(
        subscription_id: String,
        old_product_id: String,
        new_product_id: String,
    ) -> SubscriptionProductUpdatedMetadata {
        SubscriptionProductUpdatedMetadata {
            subscription_id,
            old_product_id,
            new_product_id,
        }
    }
}
