/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "name")]
pub enum SystemEvent {
    #[serde(rename = "meter.credited")]
    MeterCredited(Box<models::MeterCreditEvent>),
    #[serde(rename = "meter.reset")]
    MeterReset(Box<models::MeterResetEvent>),
    #[serde(rename = "benefit.granted")]
    BenefitGranted(Box<models::BenefitGrantedEvent>),
    #[serde(rename = "benefit.cycled")]
    BenefitCycled(Box<models::BenefitCycledEvent>),
    #[serde(rename = "benefit.updated")]
    BenefitUpdated(Box<models::BenefitUpdatedEvent>),
    #[serde(rename = "benefit.revoked")]
    BenefitRevoked(Box<models::BenefitRevokedEvent>),
    #[serde(rename = "subscription.cycled")]
    SubscriptionCycled(Box<models::SubscriptionCycledEvent>),
    #[serde(rename = "subscription.revoked")]
    SubscriptionRevoked(Box<models::SubscriptionRevokedEvent>),
    #[serde(rename = "subscription.product_updated")]
    SubscriptionProductUpdated(Box<models::SubscriptionProductUpdatedEvent>),
    #[serde(rename = "order.paid")]
    OrderPaid(Box<models::OrderPaidEvent>),
    #[serde(rename = "order.refunded")]
    OrderRefunded(Box<models::OrderRefundedEvent>),
    #[serde(rename = "customer.created")]
    CustomerCreated(Box<models::CustomerCreatedEvent>),
    #[serde(rename = "customer.updated")]
    CustomerUpdated(Box<models::CustomerUpdatedEvent>),
    #[serde(rename = "customer.deleted")]
    CustomerDeleted(Box<models::CustomerDeletedEvent>),
}

impl Default for SystemEvent {
    fn default() -> Self {
        Self::MeterCredited(Default::default())
    }
}

/// The source of the event. `system` events are created by Polar. `user` events are the one you create through our ingestion API.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Source {
    #[serde(rename = "system")]
    System,
}

impl Default for Source {
    fn default() -> Source {
        Self::System
    }
}
