/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UnitAmount : The price per unit in cents. Supports up to 12 decimal places.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnitAmount {}

impl UnitAmount {
    /// The price per unit in cents. Supports up to 12 decimal places.
    pub fn new() -> UnitAmount {
        UnitAmount {}
    }
}
