/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WalletSortProperty {
    #[serde(rename = "created_at")]
    CreatedAt,
    #[serde(rename = "-created_at")]
    CreatedAt2,
    #[serde(rename = "balance")]
    Balance,
    #[serde(rename = "-balance")]
    Balance2,
}

impl std::fmt::Display for WalletSortProperty {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CreatedAt => write!(f, "created_at"),
            Self::CreatedAt2 => write!(f, "-created_at"),
            Self::Balance => write!(f, "balance"),
            Self::Balance2 => write!(f, "-balance"),
        }
    }
}

impl Default for WalletSortProperty {
    fn default() -> WalletSortProperty {
        Self::CreatedAt
    }
}
