/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookCheckoutCreatedPayload : Sent when a new checkout is created.  **Discord & Slack support:** Basic
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookCheckoutCreatedPayload {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "data")]
    pub data: Box<models::Checkout>,
}

impl WebhookCheckoutCreatedPayload {
    /// Sent when a new checkout is created.  **Discord & Slack support:** Basic
    pub fn new(
        r#type: Type,
        timestamp: String,
        data: models::Checkout,
    ) -> WebhookCheckoutCreatedPayload {
        WebhookCheckoutCreatedPayload {
            r#type,
            timestamp,
            data: Box::new(data),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "checkout.created")]
    CheckoutCreated,
}

impl Default for Type {
    fn default() -> Type {
        Self::CheckoutCreated
    }
}
