/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookCustomerSeatRevokedPayload : Sent when a customer seat is revoked.  This event is triggered when access to a seat is revoked, either manually by the organization or automatically when a subscription is canceled.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookCustomerSeatRevokedPayload {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "data")]
    pub data: Box<models::CustomerSeat>,
}

impl WebhookCustomerSeatRevokedPayload {
    /// Sent when a customer seat is revoked.  This event is triggered when access to a seat is revoked, either manually by the organization or automatically when a subscription is canceled.
    pub fn new(
        r#type: Type,
        timestamp: String,
        data: models::CustomerSeat,
    ) -> WebhookCustomerSeatRevokedPayload {
        WebhookCustomerSeatRevokedPayload {
            r#type,
            timestamp,
            data: Box::new(data),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "customer_seat.revoked")]
    CustomerSeatRevoked,
}

impl Default for Type {
    fn default() -> Type {
        Self::CustomerSeatRevoked
    }
}
