/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookCustomerCreatedPayload : Sent when a new customer is created.  A customer can be created:  * After a successful checkout. * Programmatically via the API.  **Discord & Slack support:** Basic
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookCustomerCreatedPayload {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "data")]
    pub data: Box<models::Customer>,
}

impl WebhookCustomerCreatedPayload {
    /// Sent when a new customer is created.  A customer can be created:  * After a successful checkout. * Programmatically via the API.  **Discord & Slack support:** Basic
    pub fn new(
        r#type: Type,
        timestamp: String,
        data: models::Customer,
    ) -> WebhookCustomerCreatedPayload {
        WebhookCustomerCreatedPayload {
            r#type,
            timestamp,
            data: Box::new(data),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "customer.created")]
    CustomerCreated,
}

impl Default for Type {
    fn default() -> Type {
        Self::CustomerCreated
    }
}
