/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookBenefitGrantCreatedPayload : Sent when a new benefit grant is created.  **Discord & Slack support:** Basic
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookBenefitGrantCreatedPayload {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "data")]
    pub data: Box<models::BenefitGrantWebhook>,
}

impl WebhookBenefitGrantCreatedPayload {
    /// Sent when a new benefit grant is created.  **Discord & Slack support:** Basic
    pub fn new(
        r#type: Type,
        timestamp: String,
        data: models::BenefitGrantWebhook,
    ) -> WebhookBenefitGrantCreatedPayload {
        WebhookBenefitGrantCreatedPayload {
            r#type,
            timestamp,
            data: Box::new(data),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "benefit_grant.created")]
    BenefitGrantCreated,
}

impl Default for Type {
    fn default() -> Type {
        Self::BenefitGrantCreated
    }
}
