/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookCustomerSeatAssignedPayload : Sent when a new customer seat is assigned.  This event is triggered when a seat is assigned to a customer by the organization. The customer will receive an invitation email to claim the seat.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookCustomerSeatAssignedPayload {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "data")]
    pub data: Box<models::CustomerSeat>,
}

impl WebhookCustomerSeatAssignedPayload {
    /// Sent when a new customer seat is assigned.  This event is triggered when a seat is assigned to a customer by the organization. The customer will receive an invitation email to claim the seat.
    pub fn new(
        r#type: Type,
        timestamp: String,
        data: models::CustomerSeat,
    ) -> WebhookCustomerSeatAssignedPayload {
        WebhookCustomerSeatAssignedPayload {
            r#type,
            timestamp,
            data: Box::new(data),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "customer_seat.assigned")]
    CustomerSeatAssigned,
}

impl Default for Type {
    fn default() -> Type {
        Self::CustomerSeatAssigned
    }
}
