/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookOrderCreatedPayload : Sent when a new order is created.  A new order is created when:  * A customer purchases a one-time product. In this case, `billing_reason` is set to `purchase`. * A customer starts a subscription. In this case, `billing_reason` is set to `subscription_create`. * A subscription is renewed. In this case, `billing_reason` is set to `subscription_cycle`. * A subscription is upgraded or downgraded with an immediate proration invoice. In this case, `billing_reason` is set to `subscription_update`.  <Warning>The order might not be paid yet, so the `status` field might be `pending`.</Warning>  **Discord & Slack support:** Full
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookOrderCreatedPayload {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "data")]
    pub data: Box<models::Order>,
}

impl WebhookOrderCreatedPayload {
    /// Sent when a new order is created.  A new order is created when:  * A customer purchases a one-time product. In this case, `billing_reason` is set to `purchase`. * A customer starts a subscription. In this case, `billing_reason` is set to `subscription_create`. * A subscription is renewed. In this case, `billing_reason` is set to `subscription_cycle`. * A subscription is upgraded or downgraded with an immediate proration invoice. In this case, `billing_reason` is set to `subscription_update`.  <Warning>The order might not be paid yet, so the `status` field might be `pending`.</Warning>  **Discord & Slack support:** Full
    pub fn new(r#type: Type, timestamp: String, data: models::Order) -> WebhookOrderCreatedPayload {
        WebhookOrderCreatedPayload {
            r#type,
            timestamp,
            data: Box::new(data),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "order.created")]
    OrderCreated,
}

impl Default for Type {
    fn default() -> Type {
        Self::OrderCreated
    }
}
