/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WebhookEventType {
    #[serde(rename = "checkout.created")]
    CheckoutCreated,
    #[serde(rename = "checkout.updated")]
    CheckoutUpdated,
    #[serde(rename = "customer.created")]
    CustomerCreated,
    #[serde(rename = "customer.updated")]
    CustomerUpdated,
    #[serde(rename = "customer.deleted")]
    CustomerDeleted,
    #[serde(rename = "customer.state_changed")]
    CustomerStateChanged,
    #[serde(rename = "customer_seat.assigned")]
    CustomerSeatAssigned,
    #[serde(rename = "customer_seat.claimed")]
    CustomerSeatClaimed,
    #[serde(rename = "customer_seat.revoked")]
    CustomerSeatRevoked,
    #[serde(rename = "order.created")]
    OrderCreated,
    #[serde(rename = "order.updated")]
    OrderUpdated,
    #[serde(rename = "order.paid")]
    OrderPaid,
    #[serde(rename = "order.refunded")]
    OrderRefunded,
    #[serde(rename = "subscription.created")]
    SubscriptionCreated,
    #[serde(rename = "subscription.updated")]
    SubscriptionUpdated,
    #[serde(rename = "subscription.active")]
    SubscriptionActive,
    #[serde(rename = "subscription.canceled")]
    SubscriptionCanceled,
    #[serde(rename = "subscription.uncanceled")]
    SubscriptionUncanceled,
    #[serde(rename = "subscription.revoked")]
    SubscriptionRevoked,
    #[serde(rename = "refund.created")]
    RefundCreated,
    #[serde(rename = "refund.updated")]
    RefundUpdated,
    #[serde(rename = "product.created")]
    ProductCreated,
    #[serde(rename = "product.updated")]
    ProductUpdated,
    #[serde(rename = "benefit.created")]
    BenefitCreated,
    #[serde(rename = "benefit.updated")]
    BenefitUpdated,
    #[serde(rename = "benefit_grant.created")]
    BenefitGrantCreated,
    #[serde(rename = "benefit_grant.cycled")]
    BenefitGrantCycled,
    #[serde(rename = "benefit_grant.updated")]
    BenefitGrantUpdated,
    #[serde(rename = "benefit_grant.revoked")]
    BenefitGrantRevoked,
    #[serde(rename = "organization.updated")]
    OrganizationUpdated,
}

impl std::fmt::Display for WebhookEventType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CheckoutCreated => write!(f, "checkout.created"),
            Self::CheckoutUpdated => write!(f, "checkout.updated"),
            Self::CustomerCreated => write!(f, "customer.created"),
            Self::CustomerUpdated => write!(f, "customer.updated"),
            Self::CustomerDeleted => write!(f, "customer.deleted"),
            Self::CustomerStateChanged => write!(f, "customer.state_changed"),
            Self::CustomerSeatAssigned => write!(f, "customer_seat.assigned"),
            Self::CustomerSeatClaimed => write!(f, "customer_seat.claimed"),
            Self::CustomerSeatRevoked => write!(f, "customer_seat.revoked"),
            Self::OrderCreated => write!(f, "order.created"),
            Self::OrderUpdated => write!(f, "order.updated"),
            Self::OrderPaid => write!(f, "order.paid"),
            Self::OrderRefunded => write!(f, "order.refunded"),
            Self::SubscriptionCreated => write!(f, "subscription.created"),
            Self::SubscriptionUpdated => write!(f, "subscription.updated"),
            Self::SubscriptionActive => write!(f, "subscription.active"),
            Self::SubscriptionCanceled => write!(f, "subscription.canceled"),
            Self::SubscriptionUncanceled => write!(f, "subscription.uncanceled"),
            Self::SubscriptionRevoked => write!(f, "subscription.revoked"),
            Self::RefundCreated => write!(f, "refund.created"),
            Self::RefundUpdated => write!(f, "refund.updated"),
            Self::ProductCreated => write!(f, "product.created"),
            Self::ProductUpdated => write!(f, "product.updated"),
            Self::BenefitCreated => write!(f, "benefit.created"),
            Self::BenefitUpdated => write!(f, "benefit.updated"),
            Self::BenefitGrantCreated => write!(f, "benefit_grant.created"),
            Self::BenefitGrantCycled => write!(f, "benefit_grant.cycled"),
            Self::BenefitGrantUpdated => write!(f, "benefit_grant.updated"),
            Self::BenefitGrantRevoked => write!(f, "benefit_grant.revoked"),
            Self::OrganizationUpdated => write!(f, "organization.updated"),
        }
    }
}

impl Default for WebhookEventType {
    fn default() -> WebhookEventType {
        Self::CheckoutCreated
    }
}
