/*
 * Polar API
 *
 * Read the docs at https://polar.sh/docs/api-reference
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookEvent : A webhook event.  An event represent something that happened in the system that should be sent to the webhook endpoint.  It can be delivered multiple times until it's marked as succeeded, each one creating a new delivery.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookEvent {
    /// Creation timestamp of the object.
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "modified_at", deserialize_with = "Option::deserialize")]
    pub modified_at: Option<String>,
    /// The ID of the object.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(
        rename = "last_http_code",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_http_code: Option<Option<i32>>,
    #[serde(
        rename = "succeeded",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub succeeded: Option<Option<bool>>,
    #[serde(rename = "payload", deserialize_with = "Option::deserialize")]
    pub payload: Option<String>,
    /// The type of the webhook event.
    #[serde(rename = "type")]
    pub r#type: models::WebhookEventType,
    /// Whether this event is archived. Archived events can't be redelivered, and the payload is not accessible anymore.
    #[serde(rename = "is_archived")]
    pub is_archived: bool,
}

impl WebhookEvent {
    /// A webhook event.  An event represent something that happened in the system that should be sent to the webhook endpoint.  It can be delivered multiple times until it's marked as succeeded, each one creating a new delivery.
    pub fn new(
        created_at: String,
        modified_at: Option<String>,
        id: String,
        payload: Option<String>,
        r#type: models::WebhookEventType,
        is_archived: bool,
    ) -> WebhookEvent {
        WebhookEvent {
            created_at,
            modified_at,
            id,
            last_http_code: None,
            succeeded: None,
            payload,
            r#type,
            is_archived,
        }
    }
}
